#
# Copyright 2014 Ettus Research LLC
#

##################################################
# RFNoC Sources
##################################################
RFNOC_OOT_SRCS = \
$(addprefix /home/switchlanez/rfnoc/src/rfnoc-atsc_rx/rfnoc/fpga-src/, \
noc_block_rxfilt.v \
noc_block_fpll.v \
noc_block_dcr.v \
noc_block_agc.v \
) \

