// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="atsc_rsdecoder_impl,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k410tffg900-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.100000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=4,HLS_SYN_FF=2332,HLS_SYN_LUT=2830}" *)

module atsc_rsdecoder_impl (
        ap_clk,
        ap_rst_n,
        in_TDATA,
        in_TVALID,
        in_TREADY,
        in_TLAST,
        out_TDATA,
        out_TVALID,
        out_TREADY,
        out_TLAST
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 20'b1;
parameter    ap_ST_st2_fsm_1 = 20'b10;
parameter    ap_ST_st3_fsm_2 = 20'b100;
parameter    ap_ST_st4_fsm_3 = 20'b1000;
parameter    ap_ST_st5_fsm_4 = 20'b10000;
parameter    ap_ST_st6_fsm_5 = 20'b100000;
parameter    ap_ST_st7_fsm_6 = 20'b1000000;
parameter    ap_ST_st8_fsm_7 = 20'b10000000;
parameter    ap_ST_st9_fsm_8 = 20'b100000000;
parameter    ap_ST_st10_fsm_9 = 20'b1000000000;
parameter    ap_ST_st11_fsm_10 = 20'b10000000000;
parameter    ap_ST_st12_fsm_11 = 20'b100000000000;
parameter    ap_ST_st13_fsm_12 = 20'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 20'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 20'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 20'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 20'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 20'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 20'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 20'b10000000000000000000;
parameter    ap_true = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv7_35 = 7'b110101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv64_CC = 64'b11001100;
parameter    ap_const_lv64_CD = 64'b11001101;
parameter    ap_const_lv64_CE = 64'b11001110;
parameter    ap_const_lv64_B8 = 64'b10111000;
parameter    ap_const_lv64_B9 = 64'b10111001;
parameter    ap_const_lv64_BA = 64'b10111010;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv6_34 = 6'b110100;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv8_FC = 8'b11111100;
parameter    ap_const_lv8_FD = 8'b11111101;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv8_FE = 8'b11111110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv16_20 = 16'b100000;
parameter    ap_const_lv6_2F = 6'b101111;
parameter    ap_const_lv5_1F = 5'b11111;
parameter    ap_const_lv5_1 = 5'b1;

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_TDATA;
input   in_TVALID;
output   in_TREADY;
input  [0:0] in_TLAST;
output  [31:0] out_TDATA;
output   out_TVALID;
input   out_TREADY;
output  [0:0] out_TLAST;

reg    ap_rst_n_inv;
reg   [31:0] in_data_0_data_out;
wire    in_data_0_vld_in;
wire    in_data_0_vld_out;
reg    in_data_0_ack_out;
reg   [31:0] in_data_0_data_reg;
reg    in_data_0_areset_d;
reg    in_data_0_in_rdy = 1'b0;
reg    in_data_0_has_vld_data_reg_i;
reg    in_data_0_has_vld_data_reg = 1'b0;
wire    in_last_V_0_vld_in;
reg    in_last_V_0_ack_out;
reg    in_last_V_0_in_rdy = 1'b0;
reg    in_last_V_0_has_vld_data_reg_i;
reg    in_last_V_0_has_vld_data_reg = 1'b0;
reg   [31:0] out_data_1_data_in;
reg    out_data_1_vld_in;
reg    out_data_1_ack_in;
wire    out_data_1_ack_out;
reg   [31:0] out_data_1_data_reg;
reg    out_data_1_sRdy;
reg    out_data_1_mVld = 1'b0;
reg    out_data_1_areset_d;
reg   [0:0] out_last_V_1_data_in;
reg    out_last_V_1_vld_in;
wire    out_last_V_1_ack_out;
reg   [0:0] out_last_V_1_data_reg;
reg    out_last_V_1_sRdy;
reg    out_last_V_1_mVld = 1'b0;
reg    out_last_V_1_areset_d;
reg   [31:0] rs_d_nerrors_corrrected_count = 32'b00000000000000000000000000000000;
reg   [31:0] rs_d_bad_packet_count = 32'b00000000000000000000000000000000;
reg   [31:0] rs_d_total_packets = 32'b00000000000000000000000000000000;
reg   [31:0] reg_351_0;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm = 20'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_155;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_165;
wire   [0:0] exitcond13_fu_403_p2;
reg    ap_sig_bdd_174;
wire   [7:0] rs_out_data_assign_q0;
reg   [7:0] reg_355;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_188;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_195;
reg   [7:0] reg_384;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_205;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_212;
reg   [31:0] temp_reg_692;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_222;
wire   [15:0] rs_in_pli_flags_fu_389_p1;
reg   [15:0] rs_in_pli_flags_reg_698;
reg   [15:0] rs_in_pli_segno_reg_703;
wire   [7:0] tmp_s_fu_414_p3;
reg   [7:0] tmp_s_reg_711;
reg   [7:0] tmp_140_reg_717;
wire   [5:0] i_26_fu_454_p2;
reg   [5:0] i_26_reg_722;
wire   [6:0] i_27_fu_491_p2;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_241;
wire   [0:0] exitcond14_fu_485_p2;
reg    ap_sig_bdd_246;
reg   [9:0] tmp_101_reg_735;
wire   [4:0] tmp_114_fu_506_p1;
reg   [4:0] tmp_114_reg_740;
wire   [31:0] grp_atsc_rsdecoder_impl_decode_fu_341_ap_return;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_263;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_ap_done;
reg   [31:0] rs_d_nerrors_corrrected_count_s_reg_753;
wire   [31:0] temp_3_fu_556_p3;
wire   [7:0] tmp_143_fu_597_p3;
reg   [7:0] tmp_143_reg_766;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_282;
wire   [0:0] exitcond15_fu_591_p2;
wire   [5:0] i_28_fu_627_p2;
reg   [5:0] i_28_reg_782;
wire   [7:0] rs_out_data_assign_q1;
reg   [7:0] rs_out_data_assign_load_4_reg_792;
wire   [31:0] temp_5_fu_653_p5;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_310;
wire   [31:0] temp_4_fu_675_p1;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_325;
wire   [4:0] i_29_fu_686_p2;
reg   [4:0] i_29_reg_830;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_335;
wire   [0:0] exitcond_fu_680_p2;
reg   [7:0] rs_out_data_assign_address0;
reg    rs_out_data_assign_ce0;
reg    rs_out_data_assign_we0;
wire   [7:0] rs_out_data_assign_d0;
reg   [7:0] rs_out_data_assign_address1;
reg    rs_out_data_assign_ce1;
reg   [7:0] rs_in_data_address0;
reg    rs_in_data_ce0;
reg    rs_in_data_we0;
reg   [7:0] rs_in_data_d0;
wire   [7:0] rs_in_data_q0;
reg   [7:0] rs_in_data_address1;
reg    rs_in_data_ce1;
reg    rs_in_data_we1;
reg   [7:0] rs_in_data_d1;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_ap_start;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_ap_idle;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_ap_ready;
wire   [7:0] grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_address0;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_ce0;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_we0;
wire   [7:0] grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_d0;
wire   [7:0] grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_address0;
wire    grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_ce0;
wire   [7:0] grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_q0;
reg   [5:0] i_reg_285;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_391;
reg   [6:0] i1_reg_297;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_401;
reg   [31:0] nerrors_corrrected_i_pn_reg_308;
wire   [0:0] error_assign_fu_509_p2;
reg   [5:0] i2_reg_319;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_417;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_425;
reg   [4:0] i3_reg_330;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_436;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_444;
reg    grp_atsc_rsdecoder_impl_decode_fu_341_ap_start_ap_start_reg = 1'b0;
wire   [63:0] tmp_133_fu_428_p1;
wire   [63:0] tmp_136_fu_439_p1;
wire   [63:0] tmp_139_fu_465_p1;
wire   [63:0] tmp_142_fu_475_p1;
wire   [63:0] tmp_145_fu_611_p1;
wire   [63:0] tmp_147_fu_622_p1;
wire   [63:0] tmp_149_fu_638_p1;
wire   [63:0] tmp_151_fu_648_p1;
wire   [31:0] storemerge_i_fu_564_p2;
wire   [31:0] tmp_172_i_fu_544_p2;
wire   [31:0] tmp_175_i_fu_579_p2;
reg    ap_sig_bdd_565;
wire   [7:0] tmp_113_fu_409_p1;
wire   [7:0] tmp_112_fu_480_p1;
wire   [7:0] tmp_132_fu_422_p2;
wire   [7:0] tmp_135_fu_433_p2;
wire   [7:0] tmp_138_fu_460_p2;
wire   [7:0] tmp_141_fu_470_p2;
wire   [15:0] plinfo_flags_assign_i_i_fu_523_p2;
wire   [15:0] tmp_1_i_i_fu_515_p4;
wire   [15:0] rs_out_pli_flags_fu_528_p3;
wire   [7:0] tmp_144_fu_605_p2;
wire   [7:0] tmp_146_fu_616_p2;
wire   [7:0] tmp_148_fu_633_p2;
wire   [7:0] tmp_150_fu_643_p2;
wire   [23:0] tmp_fu_665_p4;
reg   [19:0] ap_NS_fsm;
reg    ap_sig_bdd_271;


atsc_rsdecoder_impl_rs_out_data_assign #(
    .DataWidth( 8 ),
    .AddressRange( 187 ),
    .AddressWidth( 8 ))
rs_out_data_assign_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( rs_out_data_assign_address0 ),
    .ce0( rs_out_data_assign_ce0 ),
    .we0( rs_out_data_assign_we0 ),
    .d0( rs_out_data_assign_d0 ),
    .q0( rs_out_data_assign_q0 ),
    .address1( rs_out_data_assign_address1 ),
    .ce1( rs_out_data_assign_ce1 ),
    .q1( rs_out_data_assign_q1 )
);

atsc_rsdecoder_impl_rs_in_data #(
    .DataWidth( 8 ),
    .AddressRange( 207 ),
    .AddressWidth( 8 ))
rs_in_data_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( rs_in_data_address0 ),
    .ce0( rs_in_data_ce0 ),
    .we0( rs_in_data_we0 ),
    .d0( rs_in_data_d0 ),
    .q0( rs_in_data_q0 ),
    .address1( rs_in_data_address1 ),
    .ce1( rs_in_data_ce1 ),
    .we1( rs_in_data_we1 ),
    .d1( rs_in_data_d1 )
);

atsc_rsdecoder_impl_decode grp_atsc_rsdecoder_impl_decode_fu_341(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_atsc_rsdecoder_impl_decode_fu_341_ap_start ),
    .ap_done( grp_atsc_rsdecoder_impl_decode_fu_341_ap_done ),
    .ap_idle( grp_atsc_rsdecoder_impl_decode_fu_341_ap_idle ),
    .ap_ready( grp_atsc_rsdecoder_impl_decode_fu_341_ap_ready ),
    .rs_out_data_address0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_address0 ),
    .rs_out_data_ce0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_ce0 ),
    .rs_out_data_we0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_we0 ),
    .rs_out_data_d0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_d0 ),
    .rs_in_data_address0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_address0 ),
    .rs_in_data_ce0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_ce0 ),
    .rs_in_data_q0( grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_q0 ),
    .ap_return( grp_atsc_rsdecoder_impl_decode_fu_341_ap_return )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_atsc_rsdecoder_impl_decode_fu_341_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_atsc_rsdecoder_impl_decode_fu_341_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & ~ap_sig_bdd_246 & ~(ap_const_lv1_0 == exitcond14_fu_485_p2))) begin
            grp_atsc_rsdecoder_impl_decode_fu_341_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_ready)) begin
            grp_atsc_rsdecoder_impl_decode_fu_341_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_in_data_0_has_vld_data_reg
    if (ap_rst_n_inv == 1'b1) begin
        in_data_0_has_vld_data_reg <= ap_const_logic_0;
    end else begin
        in_data_0_has_vld_data_reg <= in_data_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin : ap_ret_in_data_0_in_rdy
    if (ap_rst_n_inv == 1'b1) begin
        in_data_0_in_rdy <= ap_const_logic_0;
    end else begin
        in_data_0_in_rdy <= (in_data_0_ack_out | ~in_data_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin : ap_ret_in_last_V_0_has_vld_data_reg
    if (ap_rst_n_inv == 1'b1) begin
        in_last_V_0_has_vld_data_reg <= ap_const_logic_0;
    end else begin
        in_last_V_0_has_vld_data_reg <= in_last_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin : ap_ret_in_last_V_0_in_rdy
    if (ap_rst_n_inv == 1'b1) begin
        in_last_V_0_in_rdy <= ap_const_logic_0;
    end else begin
        in_last_V_0_in_rdy <= (in_last_V_0_ack_out | ~in_last_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin : ap_ret_out_data_1_mVld
    if (ap_rst_n_inv == 1'b1) begin
        out_data_1_mVld <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == out_data_1_vld_in)) begin
            out_data_1_mVld <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == out_data_1_ack_out)) begin
            out_data_1_mVld <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_out_last_V_1_mVld
    if (ap_rst_n_inv == 1'b1) begin
        out_last_V_1_mVld <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == out_last_V_1_vld_in)) begin
            out_last_V_1_mVld <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == out_last_V_1_ack_out)) begin
            out_last_V_1_mVld <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond14_fu_485_p2) & ~ap_sig_bdd_246)) begin
        i1_reg_297 <= i_27_fu_491_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        i1_reg_297 <= ap_const_lv7_35;
    end
end

always @ (posedge ap_clk) begin
    if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
            i2_reg_319 <= i_28_reg_782;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
            i2_reg_319 <= ap_const_lv6_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
            i3_reg_330 <= i_29_reg_830;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
            i3_reg_330 <= ap_const_lv5_10;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        i_reg_285 <= i_26_reg_722;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_reg_285 <= ap_const_lv6_1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_271) begin
        if ((ap_const_lv1_0 == error_assign_fu_509_p2)) begin
            nerrors_corrrected_i_pn_reg_308 <= grp_atsc_rsdecoder_impl_decode_fu_341_ap_return;
        end else if (~(ap_const_lv1_0 == error_assign_fu_509_p2)) begin
            nerrors_corrrected_i_pn_reg_308 <= ap_const_lv32_A;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_26_reg_722 <= i_26_fu_454_p2;
        tmp_140_reg_717 <= {{reg_351_0[ap_const_lv32_1F : ap_const_lv32_18]}};
        tmp_s_reg_711[7 : 2] <= tmp_s_fu_414_p3[7 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond15_fu_591_p2))) begin
        i_28_reg_782 <= i_28_fu_627_p2;
        tmp_143_reg_766[7 : 2] <= tmp_143_fu_597_p3[7 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & (ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2))))) begin
        i_29_reg_830 <= i_29_fu_686_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_true == ap_true)) begin
        in_data_0_areset_d <= ap_rst_n_inv;
        out_data_1_areset_d <= ap_rst_n_inv;
        out_last_V_1_areset_d <= ap_rst_n_inv;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == in_data_0_vld_in) & (ap_const_logic_1 == in_data_0_in_rdy))) begin
        in_data_0_data_reg <= in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == out_data_1_vld_in) & (ap_const_logic_1 == out_data_1_sRdy))) begin
        out_data_1_data_reg <= out_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == out_last_V_1_vld_in) & (ap_const_logic_1 == out_last_V_1_sRdy))) begin
        out_last_V_1_data_reg <= out_last_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(in_data_0_vld_out == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174))) begin
        reg_351_0 <= in_data_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14))) begin
        reg_355 <= rs_out_data_assign_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        reg_384 <= {{reg_351_0[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~((ap_const_logic_0 == out_data_1_ack_in) | (ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done)) & ~(ap_const_lv1_0 == error_assign_fu_509_p2))) begin
        rs_d_bad_packet_count <= tmp_172_i_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_logic_0 == out_data_1_ack_in) & (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9))) begin
        rs_d_nerrors_corrrected_count <= storemerge_i_fu_564_p2;
        rs_d_total_packets <= tmp_175_i_fu_579_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~((ap_const_logic_0 == out_data_1_ack_in) | (ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done)))) begin
        rs_d_nerrors_corrrected_count_s_reg_753 <= rs_d_nerrors_corrrected_count;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        rs_in_pli_flags_reg_698 <= rs_in_pli_flags_fu_389_p1;
        rs_in_pli_segno_reg_703 <= {{reg_351_0[ap_const_lv32_1F : ap_const_lv32_10]}};
        temp_reg_692 <= reg_351_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        rs_out_data_assign_load_4_reg_792 <= rs_out_data_assign_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & ~ap_sig_bdd_246 & ~(ap_const_lv1_0 == exitcond14_fu_485_p2))) begin
        tmp_101_reg_735 <= {{temp_reg_692[ap_const_lv32_F : ap_const_lv32_6]}};
        tmp_114_reg_740 <= tmp_114_fu_506_p1;
    end
end

always @ (ap_sig_bdd_417) begin
    if (ap_sig_bdd_417) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_282) begin
    if (ap_sig_bdd_282) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_188) begin
    if (ap_sig_bdd_188) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_310) begin
    if (ap_sig_bdd_310) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_425) begin
    if (ap_sig_bdd_425) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_195) begin
    if (ap_sig_bdd_195) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_325) begin
    if (ap_sig_bdd_325) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_436) begin
    if (ap_sig_bdd_436) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_335) begin
    if (ap_sig_bdd_335) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_444) begin
    if (ap_sig_bdd_444) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_155) begin
    if (ap_sig_bdd_155) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_222) begin
    if (ap_sig_bdd_222) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_165) begin
    if (ap_sig_bdd_165) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_205) begin
    if (ap_sig_bdd_205) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_391) begin
    if (ap_sig_bdd_391) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_212) begin
    if (ap_sig_bdd_212) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_401) begin
    if (ap_sig_bdd_401) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_241) begin
    if (ap_sig_bdd_241) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_263) begin
    if (ap_sig_bdd_263) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

always @ (in_data_0_vld_out or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st3_fsm_2 or exitcond13_fu_403_p2 or ap_sig_bdd_174 or ap_sig_cseq_ST_st8_fsm_7 or exitcond14_fu_485_p2 or ap_sig_bdd_246) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(in_data_0_vld_out == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174) | ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond14_fu_485_p2) & ~ap_sig_bdd_246))) begin
        in_data_0_ack_out = ap_const_logic_1;
    end else begin
        in_data_0_ack_out = ap_const_logic_0;
    end
end

always @ (in_TDATA or in_data_0_data_reg or in_data_0_has_vld_data_reg) begin
    if ((ap_const_logic_1 == in_data_0_has_vld_data_reg)) begin
        in_data_0_data_out = in_data_0_data_reg;
    end else begin
        in_data_0_data_out = in_TDATA;
    end
end

always @ (in_data_0_vld_in or in_data_0_ack_out or in_data_0_in_rdy or in_data_0_has_vld_data_reg) begin
    if (((ap_const_logic_1 == in_data_0_vld_in) & (ap_const_logic_0 == in_data_0_ack_out) & (ap_const_logic_1 == in_data_0_in_rdy))) begin
        in_data_0_has_vld_data_reg_i = ap_const_logic_1;
    end else if (((ap_const_logic_1 == in_data_0_ack_out) & (ap_const_logic_1 == in_data_0_has_vld_data_reg) & ((ap_const_logic_0 == in_data_0_vld_in) | (ap_const_logic_0 == in_data_0_in_rdy)))) begin
        in_data_0_has_vld_data_reg_i = ap_const_logic_0;
    end else begin
        in_data_0_has_vld_data_reg_i = in_data_0_has_vld_data_reg;
    end
end

always @ (in_data_0_vld_out or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st3_fsm_2 or exitcond13_fu_403_p2 or ap_sig_bdd_174 or ap_sig_cseq_ST_st8_fsm_7 or exitcond14_fu_485_p2 or ap_sig_bdd_246) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(in_data_0_vld_out == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174) | ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == exitcond14_fu_485_p2) & ~ap_sig_bdd_246))) begin
        in_last_V_0_ack_out = ap_const_logic_1;
    end else begin
        in_last_V_0_ack_out = ap_const_logic_0;
    end
end

always @ (in_last_V_0_vld_in or in_last_V_0_ack_out or in_last_V_0_in_rdy or in_last_V_0_has_vld_data_reg) begin
    if (((ap_const_logic_1 == in_last_V_0_vld_in) & (ap_const_logic_0 == in_last_V_0_ack_out) & (ap_const_logic_1 == in_last_V_0_in_rdy))) begin
        in_last_V_0_has_vld_data_reg_i = ap_const_logic_1;
    end else if (((ap_const_logic_1 == in_last_V_0_ack_out) & (ap_const_logic_1 == in_last_V_0_has_vld_data_reg) & ((ap_const_logic_0 == in_last_V_0_vld_in) | (ap_const_logic_0 == in_last_V_0_in_rdy)))) begin
        in_last_V_0_has_vld_data_reg_i = ap_const_logic_0;
    end else begin
        in_last_V_0_has_vld_data_reg_i = in_last_V_0_has_vld_data_reg;
    end
end

always @ (ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_ap_done or temp_3_fu_556_p3 or temp_5_fu_653_p5 or ap_sig_cseq_ST_st13_fsm_12 or temp_4_fu_675_p1 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or exitcond_fu_680_p2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~(ap_const_lv1_0 == exitcond_fu_680_p2)))) begin
        out_data_1_data_in = ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        out_data_1_data_in = temp_4_fu_675_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        out_data_1_data_in = temp_5_fu_653_p5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~(ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done))) begin
        out_data_1_data_in = temp_3_fu_556_p3;
    end else begin
        out_data_1_data_in = 'bx;
    end
end

always @ (out_data_1_ack_in or ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_ap_done or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or exitcond_fu_680_p2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~((ap_const_logic_0 == out_data_1_ack_in) | (ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_logic_0 == out_data_1_ack_in)) | (~(ap_const_logic_0 == out_data_1_ack_in) & (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & (ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~(ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2)))))) begin
        out_data_1_vld_in = ap_const_logic_1;
    end else begin
        out_data_1_vld_in = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_ap_done or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or exitcond_fu_680_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~(ap_const_lv1_0 == exitcond_fu_680_p2))) begin
        out_last_V_1_data_in = ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~(ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & (ap_const_lv1_0 == exitcond_fu_680_p2)))) begin
        out_last_V_1_data_in = ap_const_lv1_0;
    end else begin
        out_last_V_1_data_in = 'bx;
    end
end

always @ (out_data_1_ack_in or ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_ap_done or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or exitcond_fu_680_p2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~((ap_const_logic_0 == out_data_1_ack_in) | (ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_logic_0 == out_data_1_ack_in)) | (~(ap_const_logic_0 == out_data_1_ack_in) & (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & (ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~(ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2)))))) begin
        out_last_V_1_vld_in = ap_const_logic_1;
    end else begin
        out_last_V_1_vld_in = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st7_fsm_6 or tmp_133_fu_428_p1 or tmp_139_fu_465_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        rs_in_data_address0 = ap_const_lv64_CE;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        rs_in_data_address0 = ap_const_lv64_CC;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        rs_in_data_address0 = tmp_139_fu_465_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        rs_in_data_address0 = tmp_133_fu_428_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        rs_in_data_address0 = grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_address0;
    end else begin
        rs_in_data_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st5_fsm_4 or tmp_136_fu_439_p1 or tmp_142_fu_475_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        rs_in_data_address1 = ap_const_lv64_CD;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        rs_in_data_address1 = tmp_142_fu_475_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        rs_in_data_address1 = tmp_136_fu_439_p1;
    end else begin
        rs_in_data_address1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st7_fsm_6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6))) begin
        rs_in_data_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        rs_in_data_ce0 = grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_ce0;
    end else begin
        rs_in_data_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        rs_in_data_ce1 = ap_const_logic_1;
    end else begin
        rs_in_data_ce1 = ap_const_logic_0;
    end
end

always @ (reg_384 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st7_fsm_6 or tmp_113_fu_409_p1 or tmp_112_fu_480_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        rs_in_data_d0 = tmp_112_fu_480_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6))) begin
        rs_in_data_d0 = reg_384;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        rs_in_data_d0 = tmp_113_fu_409_p1;
    end else begin
        rs_in_data_d0 = 'bx;
    end
end

always @ (reg_351_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or tmp_140_reg_717 or ap_sig_cseq_ST_st5_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        rs_in_data_d1 = tmp_140_reg_717;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        rs_in_data_d1 = {{reg_351_0[ap_const_lv32_F : ap_const_lv32_8]}};
    end else begin
        rs_in_data_d1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st7_fsm_6) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6))) begin
        rs_in_data_we0 = ap_const_logic_1;
    end else begin
        rs_in_data_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        rs_in_data_we1 = ap_const_logic_1;
    end else begin
        rs_in_data_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or exitcond15_fu_591_p2 or grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_address0 or tmp_145_fu_611_p1 or tmp_151_fu_648_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        rs_out_data_assign_address0 = ap_const_lv64_BA;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        rs_out_data_assign_address0 = tmp_151_fu_648_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~(ap_const_lv1_0 == exitcond15_fu_591_p2))) begin
        rs_out_data_assign_address0 = ap_const_lv64_B8;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond15_fu_591_p2))) begin
        rs_out_data_assign_address0 = tmp_145_fu_611_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        rs_out_data_assign_address0 = grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_address0;
    end else begin
        rs_out_data_assign_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st11_fsm_10 or tmp_147_fu_622_p1 or tmp_149_fu_638_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        rs_out_data_assign_address1 = ap_const_lv64_B9;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        rs_out_data_assign_address1 = tmp_149_fu_638_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        rs_out_data_assign_address1 = tmp_147_fu_622_p1;
    end else begin
        rs_out_data_assign_address1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or exitcond15_fu_591_p2 or grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_ce0) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond15_fu_591_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~(ap_const_lv1_0 == exitcond15_fu_591_p2)))) begin
        rs_out_data_assign_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        rs_out_data_assign_ce0 = grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_ce0;
    end else begin
        rs_out_data_assign_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st11_fsm_10) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        rs_out_data_assign_ce1 = ap_const_logic_1;
    end else begin
        rs_out_data_assign_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_we0) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        rs_out_data_assign_we0 = grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_we0;
    end else begin
        rs_out_data_assign_we0 = ap_const_logic_0;
    end
end
always @ (in_data_0_vld_out or out_data_1_ack_in or ap_CS_fsm or exitcond13_fu_403_p2 or ap_sig_bdd_174 or exitcond14_fu_485_p2 or ap_sig_bdd_246 or grp_atsc_rsdecoder_impl_decode_fu_341_ap_done or exitcond15_fu_591_p2 or exitcond_fu_680_p2 or ap_sig_bdd_565) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(in_data_0_vld_out == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((~(exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else if (((exitcond13_fu_403_p2 == ap_const_lv1_0) & ~ap_sig_bdd_174)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            if (((ap_const_lv1_0 == exitcond14_fu_485_p2) & ~ap_sig_bdd_246)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else if ((~ap_sig_bdd_246 & ~(ap_const_lv1_0 == exitcond14_fu_485_p2))) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st9_fsm_8 : 
        begin
            if (~((ap_const_logic_0 == out_data_1_ack_in) | (ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done))) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st10_fsm_9 : 
        begin
            if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st11_fsm_10 : 
        begin
            if (~(ap_const_lv1_0 == exitcond15_fu_591_p2)) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end
        end
        ap_ST_st14_fsm_13 : 
        begin
            if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end
        end
        ap_ST_st17_fsm_16 : 
        begin
            if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end
        end
        ap_ST_st18_fsm_17 : 
        begin
            if ((~(ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2))))) begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end else if (((ap_const_lv1_0 == exitcond_fu_680_p2) & ~(((ap_const_logic_0 == out_data_1_ack_in) & (ap_const_lv1_0 == exitcond_fu_680_p2)) | ((ap_const_logic_0 == out_data_1_ack_in) & ~(ap_const_lv1_0 == exitcond_fu_680_p2))))) begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end
        end
        ap_ST_st19_fsm_18 : 
        begin
            if (~(ap_const_logic_0 == out_data_1_ack_in)) begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end else begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end
        end
        ap_ST_st20_fsm_19 : 
        begin
            if (~((ap_const_logic_0 == out_data_1_ack_in) | ap_sig_bdd_565)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_155 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_165 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (in_data_0_vld_out or exitcond13_fu_403_p2) begin
    ap_sig_bdd_174 = (((in_data_0_vld_out == ap_const_logic_0) & (exitcond13_fu_403_p2 == ap_const_lv1_0)) | ((in_data_0_vld_out == ap_const_logic_0) & ~(exitcond13_fu_403_p2 == ap_const_lv1_0)));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_188 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_195 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_205 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_212 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_222 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_241 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end


always @ (in_data_0_vld_out or exitcond14_fu_485_p2) begin
    ap_sig_bdd_246 = ((in_data_0_vld_out == ap_const_logic_0) & (ap_const_lv1_0 == exitcond14_fu_485_p2));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_263 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end


always @ (out_data_1_ack_in or ap_sig_cseq_ST_st9_fsm_8 or grp_atsc_rsdecoder_impl_decode_fu_341_ap_done) begin
    ap_sig_bdd_271 = ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~((ap_const_logic_0 == out_data_1_ack_in) | (ap_const_logic_0 == grp_atsc_rsdecoder_impl_decode_fu_341_ap_done)));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_282 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_310 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_325 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_335 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_391 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_401 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_417 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_425 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_436 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_444 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end


always @ (out_data_1_sRdy or out_last_V_1_sRdy) begin
    ap_sig_bdd_565 = ((out_data_1_sRdy == ap_const_logic_0) | (out_last_V_1_sRdy == ap_const_logic_0));
end

assign error_assign_fu_509_p2 = (grp_atsc_rsdecoder_impl_decode_fu_341_ap_return == ap_const_lv32_FFFFFFFF? 1'b1: 1'b0);

assign exitcond13_fu_403_p2 = (i_reg_285 == ap_const_lv6_34? 1'b1: 1'b0);

assign exitcond14_fu_485_p2 = (i1_reg_297 == ap_const_lv7_40? 1'b1: 1'b0);

assign exitcond15_fu_591_p2 = (i2_reg_319 == ap_const_lv6_2F? 1'b1: 1'b0);

assign exitcond_fu_680_p2 = (i3_reg_330 == ap_const_lv5_1F? 1'b1: 1'b0);

assign grp_atsc_rsdecoder_impl_decode_fu_341_ap_start = grp_atsc_rsdecoder_impl_decode_fu_341_ap_start_ap_start_reg;

assign grp_atsc_rsdecoder_impl_decode_fu_341_rs_in_data_q0 = rs_in_data_q0;

assign i_26_fu_454_p2 = (ap_const_lv6_1 + i_reg_285);

assign i_27_fu_491_p2 = (i1_reg_297 + ap_const_lv7_1);

assign i_28_fu_627_p2 = (i2_reg_319 + ap_const_lv6_1);

assign i_29_fu_686_p2 = (i3_reg_330 + ap_const_lv5_1);

assign in_TREADY = in_last_V_0_in_rdy;

assign in_data_0_vld_in = in_TVALID;

assign in_data_0_vld_out = ((in_TVALID | in_data_0_has_vld_data_reg) & ~in_data_0_areset_d);

assign in_last_V_0_vld_in = in_TVALID;

assign out_TDATA = out_data_1_data_reg;

assign out_TLAST = out_last_V_1_data_reg;

assign out_TVALID = out_last_V_1_mVld;


always @ (out_TREADY or out_data_1_mVld or out_data_1_areset_d) begin
    out_data_1_ack_in = (~out_data_1_areset_d & (out_TREADY | ~out_data_1_mVld));
end

assign out_data_1_ack_out = out_TREADY;


always @ (out_TREADY or out_data_1_mVld or out_data_1_areset_d) begin
    out_data_1_sRdy = (~out_data_1_areset_d & (out_TREADY | ~out_data_1_mVld));
end

assign out_last_V_1_ack_out = out_TREADY;


always @ (out_TREADY or out_last_V_1_mVld or out_last_V_1_areset_d) begin
    out_last_V_1_sRdy = (~out_last_V_1_areset_d & (out_TREADY | ~out_last_V_1_mVld));
end

assign plinfo_flags_assign_i_i_fu_523_p2 = (rs_in_pli_flags_reg_698 | ap_const_lv16_20);

assign rs_in_pli_flags_fu_389_p1 = reg_351_0[15:0];

assign rs_out_data_assign_d0 = grp_atsc_rsdecoder_impl_decode_fu_341_rs_out_data_d0;

assign rs_out_pli_flags_fu_528_p3 = ((error_assign_fu_509_p2[0:0] === 1'b1) ? plinfo_flags_assign_i_i_fu_523_p2 : tmp_1_i_i_fu_515_p4);

assign storemerge_i_fu_564_p2 = (rs_d_nerrors_corrrected_count_s_reg_753 + nerrors_corrrected_i_pn_reg_308);

assign temp_3_fu_556_p3 = {{rs_in_pli_segno_reg_703}, {rs_out_pli_flags_fu_528_p3}};

assign temp_4_fu_675_p1 = tmp_fu_665_p4;

assign temp_5_fu_653_p5 = {{{{rs_out_data_assign_q0}, {rs_out_data_assign_q1}}, {rs_out_data_assign_load_4_reg_792}}, {reg_355}};

assign tmp_112_fu_480_p1 = reg_351_0[7:0];

assign tmp_113_fu_409_p1 = reg_351_0[7:0];

assign tmp_114_fu_506_p1 = temp_reg_692[4:0];

assign tmp_132_fu_422_p2 = ($signed(ap_const_lv8_FC) + $signed(tmp_s_fu_414_p3));

assign tmp_133_fu_428_p1 = tmp_132_fu_422_p2;

assign tmp_135_fu_433_p2 = ($signed(ap_const_lv8_FD) + $signed(tmp_s_fu_414_p3));

assign tmp_136_fu_439_p1 = tmp_135_fu_433_p2;

assign tmp_138_fu_460_p2 = ($signed(ap_const_lv8_FE) + $signed(tmp_s_reg_711));

assign tmp_139_fu_465_p1 = tmp_138_fu_460_p2;

assign tmp_141_fu_470_p2 = ($signed(ap_const_lv8_FF) + $signed(tmp_s_reg_711));

assign tmp_142_fu_475_p1 = tmp_141_fu_470_p2;

assign tmp_143_fu_597_p3 = {{i2_reg_319}, {ap_const_lv2_0}};

assign tmp_144_fu_605_p2 = ($signed(tmp_143_fu_597_p3) + $signed(ap_const_lv8_FC));

assign tmp_145_fu_611_p1 = tmp_144_fu_605_p2;

assign tmp_146_fu_616_p2 = ($signed(tmp_143_fu_597_p3) + $signed(ap_const_lv8_FD));

assign tmp_147_fu_622_p1 = tmp_146_fu_616_p2;

assign tmp_148_fu_633_p2 = ($signed(tmp_143_reg_766) + $signed(ap_const_lv8_FE));

assign tmp_149_fu_638_p1 = tmp_148_fu_633_p2;

assign tmp_150_fu_643_p2 = ($signed(tmp_143_reg_766) + $signed(ap_const_lv8_FF));

assign tmp_151_fu_648_p1 = tmp_150_fu_643_p2;

assign tmp_172_i_fu_544_p2 = (rs_d_bad_packet_count + ap_const_lv32_1);

assign tmp_175_i_fu_579_p2 = (rs_d_total_packets + ap_const_lv32_1);

assign tmp_1_i_i_fu_515_p4 = {{{tmp_101_reg_735}, {ap_const_lv1_0}}, {tmp_114_reg_740}};

assign tmp_fu_665_p4 = {{{rs_out_data_assign_q0}, {rs_out_data_assign_q1}}, {reg_355}};

assign tmp_s_fu_414_p3 = {{i_reg_285}, {ap_const_lv2_0}};
always @ (posedge ap_clk) begin
    tmp_s_reg_711[1:0] <= 2'b00;
    tmp_143_reg_766[1:0] <= 2'b00;
end



endmodule //atsc_rsdecoder_impl

