

/* this file was generated by volk template utils, do not edit! */

/*
 * Copyright 2011-2012 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_LIBVOLK_MACHINES_H
#define INCLUDED_LIBVOLK_MACHINES_H

#include <volk/volk_common.h>
#include <volk/volk_typedefs.h>

#include <stdbool.h>
#include <stdlib.h>

__VOLK_DECL_BEGIN

struct volk_machine {
    const unsigned int caps; //capabilities (i.e., archs compiled into this machine, in the volk_get_lvarch format)
    const char *name;
    const size_t alignment; //the maximum byte alignment required for functions in this library
    const char *volk_32f_s32f_convert_32i_name;
    const char *volk_32f_s32f_convert_32i_impl_names[22];
    const int volk_32f_s32f_convert_32i_impl_deps[22];
    const bool volk_32f_s32f_convert_32i_impl_alignment[22];
    const p_32f_s32f_convert_32i volk_32f_s32f_convert_32i_impls[22];
    const size_t volk_32f_s32f_convert_32i_n_impls;
    const char *volk_16ic_s32f_deinterleave_real_32f_name;
    const char *volk_16ic_s32f_deinterleave_real_32f_impl_names[22];
    const int volk_16ic_s32f_deinterleave_real_32f_impl_deps[22];
    const bool volk_16ic_s32f_deinterleave_real_32f_impl_alignment[22];
    const p_16ic_s32f_deinterleave_real_32f volk_16ic_s32f_deinterleave_real_32f_impls[22];
    const size_t volk_16ic_s32f_deinterleave_real_32f_n_impls;
    const char *volk_32fc_s32f_power_32fc_name;
    const char *volk_32fc_s32f_power_32fc_impl_names[22];
    const int volk_32fc_s32f_power_32fc_impl_deps[22];
    const bool volk_32fc_s32f_power_32fc_impl_alignment[22];
    const p_32fc_s32f_power_32fc volk_32fc_s32f_power_32fc_impls[22];
    const size_t volk_32fc_s32f_power_32fc_n_impls;
    const char *volk_32fc_x2_multiply_32fc_name;
    const char *volk_32fc_x2_multiply_32fc_impl_names[22];
    const int volk_32fc_x2_multiply_32fc_impl_deps[22];
    const bool volk_32fc_x2_multiply_32fc_impl_alignment[22];
    const p_32fc_x2_multiply_32fc volk_32fc_x2_multiply_32fc_impls[22];
    const size_t volk_32fc_x2_multiply_32fc_n_impls;
    const char *volk_16i_max_star_16i_name;
    const char *volk_16i_max_star_16i_impl_names[22];
    const int volk_16i_max_star_16i_impl_deps[22];
    const bool volk_16i_max_star_16i_impl_alignment[22];
    const p_16i_max_star_16i volk_16i_max_star_16i_impls[22];
    const size_t volk_16i_max_star_16i_n_impls;
    const char *volk_32f_8u_polarbutterfly_32f_name;
    const char *volk_32f_8u_polarbutterfly_32f_impl_names[22];
    const int volk_32f_8u_polarbutterfly_32f_impl_deps[22];
    const bool volk_32f_8u_polarbutterfly_32f_impl_alignment[22];
    const p_32f_8u_polarbutterfly_32f volk_32f_8u_polarbutterfly_32f_impls[22];
    const size_t volk_32f_8u_polarbutterfly_32f_n_impls;
    const char *volk_32i_x2_and_32i_name;
    const char *volk_32i_x2_and_32i_impl_names[22];
    const int volk_32i_x2_and_32i_impl_deps[22];
    const bool volk_32i_x2_and_32i_impl_alignment[22];
    const p_32i_x2_and_32i volk_32i_x2_and_32i_impls[22];
    const size_t volk_32i_x2_and_32i_n_impls;
    const char *volk_32f_s32f_convert_8i_name;
    const char *volk_32f_s32f_convert_8i_impl_names[22];
    const int volk_32f_s32f_convert_8i_impl_deps[22];
    const bool volk_32f_s32f_convert_8i_impl_alignment[22];
    const p_32f_s32f_convert_8i volk_32f_s32f_convert_8i_impls[22];
    const size_t volk_32f_s32f_convert_8i_n_impls;
    const char *volk_8u_x3_encodepolar_8u_x2_name;
    const char *volk_8u_x3_encodepolar_8u_x2_impl_names[22];
    const int volk_8u_x3_encodepolar_8u_x2_impl_deps[22];
    const bool volk_8u_x3_encodepolar_8u_x2_impl_alignment[22];
    const p_8u_x3_encodepolar_8u_x2 volk_8u_x3_encodepolar_8u_x2_impls[22];
    const size_t volk_8u_x3_encodepolar_8u_x2_n_impls;
    const char *volk_32f_x2_pow_32f_name;
    const char *volk_32f_x2_pow_32f_impl_names[22];
    const int volk_32f_x2_pow_32f_impl_deps[22];
    const bool volk_32f_x2_pow_32f_impl_alignment[22];
    const p_32f_x2_pow_32f volk_32f_x2_pow_32f_impls[22];
    const size_t volk_32f_x2_pow_32f_n_impls;
    const char *volk_32fc_s32f_atan2_32f_name;
    const char *volk_32fc_s32f_atan2_32f_impl_names[22];
    const int volk_32fc_s32f_atan2_32f_impl_deps[22];
    const bool volk_32fc_s32f_atan2_32f_impl_alignment[22];
    const p_32fc_s32f_atan2_32f volk_32fc_s32f_atan2_32f_impls[22];
    const size_t volk_32fc_s32f_atan2_32f_n_impls;
    const char *volk_32f_acos_32f_name;
    const char *volk_32f_acos_32f_impl_names[22];
    const int volk_32f_acos_32f_impl_deps[22];
    const bool volk_32f_acos_32f_impl_alignment[22];
    const p_32f_acos_32f volk_32f_acos_32f_impls[22];
    const size_t volk_32f_acos_32f_n_impls;
    const char *volk_32i_x2_or_32i_name;
    const char *volk_32i_x2_or_32i_impl_names[22];
    const int volk_32i_x2_or_32i_impl_deps[22];
    const bool volk_32i_x2_or_32i_impl_alignment[22];
    const p_32i_x2_or_32i volk_32i_x2_or_32i_impls[22];
    const size_t volk_32i_x2_or_32i_n_impls;
    const char *volk_64u_byteswappuppet_64u_name;
    const char *volk_64u_byteswappuppet_64u_impl_names[22];
    const int volk_64u_byteswappuppet_64u_impl_deps[22];
    const bool volk_64u_byteswappuppet_64u_impl_alignment[22];
    const p_64u_byteswappuppet_64u volk_64u_byteswappuppet_64u_impls[22];
    const size_t volk_64u_byteswappuppet_64u_n_impls;
    const char *volk_64u_popcnt_name;
    const char *volk_64u_popcnt_impl_names[22];
    const int volk_64u_popcnt_impl_deps[22];
    const bool volk_64u_popcnt_impl_alignment[22];
    const p_64u_popcnt volk_64u_popcnt_impls[22];
    const size_t volk_64u_popcnt_n_impls;
    const char *volk_32f_cos_32f_name;
    const char *volk_32f_cos_32f_impl_names[22];
    const int volk_32f_cos_32f_impl_deps[22];
    const bool volk_32f_cos_32f_impl_alignment[22];
    const p_32f_cos_32f volk_32f_cos_32f_impls[22];
    const size_t volk_32f_cos_32f_n_impls;
    const char *volk_32f_8u_polarbutterflypuppet_32f_name;
    const char *volk_32f_8u_polarbutterflypuppet_32f_impl_names[22];
    const int volk_32f_8u_polarbutterflypuppet_32f_impl_deps[22];
    const bool volk_32f_8u_polarbutterflypuppet_32f_impl_alignment[22];
    const p_32f_8u_polarbutterflypuppet_32f volk_32f_8u_polarbutterflypuppet_32f_impls[22];
    const size_t volk_32f_8u_polarbutterflypuppet_32f_n_impls;
    const char *volk_8u_x4_conv_k7_r2_8u_name;
    const char *volk_8u_x4_conv_k7_r2_8u_impl_names[22];
    const int volk_8u_x4_conv_k7_r2_8u_impl_deps[22];
    const bool volk_8u_x4_conv_k7_r2_8u_impl_alignment[22];
    const p_8u_x4_conv_k7_r2_8u volk_8u_x4_conv_k7_r2_8u_impls[22];
    const size_t volk_8u_x4_conv_k7_r2_8u_n_impls;
    const char *volk_32i_s32f_convert_32f_name;
    const char *volk_32i_s32f_convert_32f_impl_names[22];
    const int volk_32i_s32f_convert_32f_impl_deps[22];
    const bool volk_32i_s32f_convert_32f_impl_alignment[22];
    const p_32i_s32f_convert_32f volk_32i_s32f_convert_32f_impls[22];
    const size_t volk_32i_s32f_convert_32f_n_impls;
    const char *volk_32f_x2_dot_prod_32f_name;
    const char *volk_32f_x2_dot_prod_32f_impl_names[22];
    const int volk_32f_x2_dot_prod_32f_impl_deps[22];
    const bool volk_32f_x2_dot_prod_32f_impl_alignment[22];
    const p_32f_x2_dot_prod_32f volk_32f_x2_dot_prod_32f_impls[22];
    const size_t volk_32f_x2_dot_prod_32f_n_impls;
    const char *volk_32f_x2_min_32f_name;
    const char *volk_32f_x2_min_32f_impl_names[22];
    const int volk_32f_x2_min_32f_impl_deps[22];
    const bool volk_32f_x2_min_32f_impl_alignment[22];
    const p_32f_x2_min_32f volk_32f_x2_min_32f_impls[22];
    const size_t volk_32f_x2_min_32f_n_impls;
    const char *volk_32f_sin_32f_name;
    const char *volk_32f_sin_32f_impl_names[22];
    const int volk_32f_sin_32f_impl_deps[22];
    const bool volk_32f_sin_32f_impl_alignment[22];
    const p_32f_sin_32f volk_32f_sin_32f_impls[22];
    const size_t volk_32f_sin_32f_n_impls;
    const char *volk_32f_x2_s32f_interleave_16ic_name;
    const char *volk_32f_x2_s32f_interleave_16ic_impl_names[22];
    const int volk_32f_x2_s32f_interleave_16ic_impl_deps[22];
    const bool volk_32f_x2_s32f_interleave_16ic_impl_alignment[22];
    const p_32f_x2_s32f_interleave_16ic volk_32f_x2_s32f_interleave_16ic_impls[22];
    const size_t volk_32f_x2_s32f_interleave_16ic_n_impls;
    const char *volk_32f_s32f_32f_fm_detect_32f_name;
    const char *volk_32f_s32f_32f_fm_detect_32f_impl_names[22];
    const int volk_32f_s32f_32f_fm_detect_32f_impl_deps[22];
    const bool volk_32f_s32f_32f_fm_detect_32f_impl_alignment[22];
    const p_32f_s32f_32f_fm_detect_32f volk_32f_s32f_32f_fm_detect_32f_impls[22];
    const size_t volk_32f_s32f_32f_fm_detect_32f_n_impls;
    const char *volk_32fc_x2_s32f_square_dist_scalar_mult_32f_name;
    const char *volk_32fc_x2_s32f_square_dist_scalar_mult_32f_impl_names[22];
    const int volk_32fc_x2_s32f_square_dist_scalar_mult_32f_impl_deps[22];
    const bool volk_32fc_x2_s32f_square_dist_scalar_mult_32f_impl_alignment[22];
    const p_32fc_x2_s32f_square_dist_scalar_mult_32f volk_32fc_x2_s32f_square_dist_scalar_mult_32f_impls[22];
    const size_t volk_32fc_x2_s32f_square_dist_scalar_mult_32f_n_impls;
    const char *volk_32f_sqrt_32f_name;
    const char *volk_32f_sqrt_32f_impl_names[22];
    const int volk_32f_sqrt_32f_impl_deps[22];
    const bool volk_32f_sqrt_32f_impl_alignment[22];
    const p_32f_sqrt_32f volk_32f_sqrt_32f_impls[22];
    const size_t volk_32f_sqrt_32f_n_impls;
    const char *volk_32fc_deinterleave_64f_x2_name;
    const char *volk_32fc_deinterleave_64f_x2_impl_names[22];
    const int volk_32fc_deinterleave_64f_x2_impl_deps[22];
    const bool volk_32fc_deinterleave_64f_x2_impl_alignment[22];
    const p_32fc_deinterleave_64f_x2 volk_32fc_deinterleave_64f_x2_impls[22];
    const size_t volk_32fc_deinterleave_64f_x2_n_impls;
    const char *volk_32f_s32f_convert_16i_name;
    const char *volk_32f_s32f_convert_16i_impl_names[22];
    const int volk_32f_s32f_convert_16i_impl_deps[22];
    const bool volk_32f_s32f_convert_16i_impl_alignment[22];
    const p_32f_s32f_convert_16i volk_32f_s32f_convert_16i_impls[22];
    const size_t volk_32f_s32f_convert_16i_n_impls;
    const char *volk_8u_x3_encodepolarpuppet_8u_name;
    const char *volk_8u_x3_encodepolarpuppet_8u_impl_names[22];
    const int volk_8u_x3_encodepolarpuppet_8u_impl_deps[22];
    const bool volk_8u_x3_encodepolarpuppet_8u_impl_alignment[22];
    const p_8u_x3_encodepolarpuppet_8u volk_8u_x3_encodepolarpuppet_8u_impls[22];
    const size_t volk_8u_x3_encodepolarpuppet_8u_n_impls;
    const char *volk_32fc_32f_multiply_32fc_name;
    const char *volk_32fc_32f_multiply_32fc_impl_names[22];
    const int volk_32fc_32f_multiply_32fc_impl_deps[22];
    const bool volk_32fc_32f_multiply_32fc_impl_alignment[22];
    const p_32fc_32f_multiply_32fc volk_32fc_32f_multiply_32fc_impls[22];
    const size_t volk_32fc_32f_multiply_32fc_n_impls;
    const char *volk_32fc_s32f_deinterleave_real_16i_name;
    const char *volk_32fc_s32f_deinterleave_real_16i_impl_names[22];
    const int volk_32fc_s32f_deinterleave_real_16i_impl_deps[22];
    const bool volk_32fc_s32f_deinterleave_real_16i_impl_alignment[22];
    const p_32fc_s32f_deinterleave_real_16i volk_32fc_s32f_deinterleave_real_16i_impls[22];
    const size_t volk_32fc_s32f_deinterleave_real_16i_n_impls;
    const char *volk_32fc_deinterleave_imag_32f_name;
    const char *volk_32fc_deinterleave_imag_32f_impl_names[22];
    const int volk_32fc_deinterleave_imag_32f_impl_deps[22];
    const bool volk_32fc_deinterleave_imag_32f_impl_alignment[22];
    const p_32fc_deinterleave_imag_32f volk_32fc_deinterleave_imag_32f_impls[22];
    const size_t volk_32fc_deinterleave_imag_32f_n_impls;
    const char *volk_16ic_s32f_deinterleave_32f_x2_name;
    const char *volk_16ic_s32f_deinterleave_32f_x2_impl_names[22];
    const int volk_16ic_s32f_deinterleave_32f_x2_impl_deps[22];
    const bool volk_16ic_s32f_deinterleave_32f_x2_impl_alignment[22];
    const p_16ic_s32f_deinterleave_32f_x2 volk_16ic_s32f_deinterleave_32f_x2_impls[22];
    const size_t volk_16ic_s32f_deinterleave_32f_x2_n_impls;
    const char *volk_32u_byteswap_name;
    const char *volk_32u_byteswap_impl_names[22];
    const int volk_32u_byteswap_impl_deps[22];
    const bool volk_32u_byteswap_impl_alignment[22];
    const p_32u_byteswap volk_32u_byteswap_impls[22];
    const size_t volk_32u_byteswap_n_impls;
    const char *volk_32f_s32f_power_32f_name;
    const char *volk_32f_s32f_power_32f_impl_names[22];
    const int volk_32f_s32f_power_32f_impl_deps[22];
    const bool volk_32f_s32f_power_32f_impl_alignment[22];
    const p_32f_s32f_power_32f volk_32f_s32f_power_32f_impls[22];
    const size_t volk_32f_s32f_power_32f_n_impls;
    const char *volk_32fc_s32fc_rotatorpuppet_32fc_name;
    const char *volk_32fc_s32fc_rotatorpuppet_32fc_impl_names[22];
    const int volk_32fc_s32fc_rotatorpuppet_32fc_impl_deps[22];
    const bool volk_32fc_s32fc_rotatorpuppet_32fc_impl_alignment[22];
    const p_32fc_s32fc_rotatorpuppet_32fc volk_32fc_s32fc_rotatorpuppet_32fc_impls[22];
    const size_t volk_32fc_s32fc_rotatorpuppet_32fc_n_impls;
    const char *volk_32u_popcntpuppet_32u_name;
    const char *volk_32u_popcntpuppet_32u_impl_names[22];
    const int volk_32u_popcntpuppet_32u_impl_deps[22];
    const bool volk_32u_popcntpuppet_32u_impl_alignment[22];
    const p_32u_popcntpuppet_32u volk_32u_popcntpuppet_32u_impls[22];
    const size_t volk_32u_popcntpuppet_32u_n_impls;
    const char *volk_8ic_x2_multiply_conjugate_16ic_name;
    const char *volk_8ic_x2_multiply_conjugate_16ic_impl_names[22];
    const int volk_8ic_x2_multiply_conjugate_16ic_impl_deps[22];
    const bool volk_8ic_x2_multiply_conjugate_16ic_impl_alignment[22];
    const p_8ic_x2_multiply_conjugate_16ic volk_8ic_x2_multiply_conjugate_16ic_impls[22];
    const size_t volk_8ic_x2_multiply_conjugate_16ic_n_impls;
    const char *volk_32f_x2_divide_32f_name;
    const char *volk_32f_x2_divide_32f_impl_names[22];
    const int volk_32f_x2_divide_32f_impl_deps[22];
    const bool volk_32f_x2_divide_32f_impl_alignment[22];
    const p_32f_x2_divide_32f volk_32f_x2_divide_32f_impls[22];
    const size_t volk_32f_x2_divide_32f_n_impls;
    const char *volk_32f_index_max_16u_name;
    const char *volk_32f_index_max_16u_impl_names[22];
    const int volk_32f_index_max_16u_impl_deps[22];
    const bool volk_32f_index_max_16u_impl_alignment[22];
    const p_32f_index_max_16u volk_32f_index_max_16u_impls[22];
    const size_t volk_32f_index_max_16u_n_impls;
    const char *volk_32f_s32f_multiply_32f_name;
    const char *volk_32f_s32f_multiply_32f_impl_names[22];
    const int volk_32f_s32f_multiply_32f_impl_deps[22];
    const bool volk_32f_s32f_multiply_32f_impl_alignment[22];
    const p_32f_s32f_multiply_32f volk_32f_s32f_multiply_32f_impls[22];
    const size_t volk_32f_s32f_multiply_32f_n_impls;
    const char *volk_16i_permute_and_scalar_add_name;
    const char *volk_16i_permute_and_scalar_add_impl_names[22];
    const int volk_16i_permute_and_scalar_add_impl_deps[22];
    const bool volk_16i_permute_and_scalar_add_impl_alignment[22];
    const p_16i_permute_and_scalar_add volk_16i_permute_and_scalar_add_impls[22];
    const size_t volk_16i_permute_and_scalar_add_n_impls;
    const char *volk_32u_popcnt_name;
    const char *volk_32u_popcnt_impl_names[22];
    const int volk_32u_popcnt_impl_deps[22];
    const bool volk_32u_popcnt_impl_alignment[22];
    const p_32u_popcnt volk_32u_popcnt_impls[22];
    const size_t volk_32u_popcnt_n_impls;
    const char *volk_16ic_deinterleave_real_8i_name;
    const char *volk_16ic_deinterleave_real_8i_impl_names[22];
    const int volk_16ic_deinterleave_real_8i_impl_deps[22];
    const bool volk_16ic_deinterleave_real_8i_impl_alignment[22];
    const p_16ic_deinterleave_real_8i volk_16ic_deinterleave_real_8i_impls[22];
    const size_t volk_16ic_deinterleave_real_8i_n_impls;
    const char *volk_32f_stddev_and_mean_32f_x2_name;
    const char *volk_32f_stddev_and_mean_32f_x2_impl_names[22];
    const int volk_32f_stddev_and_mean_32f_x2_impl_deps[22];
    const bool volk_32f_stddev_and_mean_32f_x2_impl_alignment[22];
    const p_32f_stddev_and_mean_32f_x2 volk_32f_stddev_and_mean_32f_x2_impls[22];
    const size_t volk_32f_stddev_and_mean_32f_x2_n_impls;
    const char *volk_16i_x4_quad_max_star_16i_name;
    const char *volk_16i_x4_quad_max_star_16i_impl_names[22];
    const int volk_16i_x4_quad_max_star_16i_impl_deps[22];
    const bool volk_16i_x4_quad_max_star_16i_impl_alignment[22];
    const p_16i_x4_quad_max_star_16i volk_16i_x4_quad_max_star_16i_impls[22];
    const size_t volk_16i_x4_quad_max_star_16i_n_impls;
    const char *volk_32fc_x2_divide_32fc_name;
    const char *volk_32fc_x2_divide_32fc_impl_names[22];
    const int volk_32fc_x2_divide_32fc_impl_deps[22];
    const bool volk_32fc_x2_divide_32fc_impl_alignment[22];
    const p_32fc_x2_divide_32fc volk_32fc_x2_divide_32fc_impls[22];
    const size_t volk_32fc_x2_divide_32fc_n_impls;
    const char *volk_16ic_deinterleave_16i_x2_name;
    const char *volk_16ic_deinterleave_16i_x2_impl_names[22];
    const int volk_16ic_deinterleave_16i_x2_impl_deps[22];
    const bool volk_16ic_deinterleave_16i_x2_impl_alignment[22];
    const p_16ic_deinterleave_16i_x2 volk_16ic_deinterleave_16i_x2_impls[22];
    const size_t volk_16ic_deinterleave_16i_x2_n_impls;
    const char *volk_16u_byteswap_name;
    const char *volk_16u_byteswap_impl_names[22];
    const int volk_16u_byteswap_impl_deps[22];
    const bool volk_16u_byteswap_impl_alignment[22];
    const p_16u_byteswap volk_16u_byteswap_impls[22];
    const size_t volk_16u_byteswap_n_impls;
    const char *volk_32f_index_max_32u_name;
    const char *volk_32f_index_max_32u_impl_names[22];
    const int volk_32f_index_max_32u_impl_deps[22];
    const bool volk_32f_index_max_32u_impl_alignment[22];
    const p_32f_index_max_32u volk_32f_index_max_32u_impls[22];
    const size_t volk_32f_index_max_32u_n_impls;
    const char *volk_16i_32fc_dot_prod_32fc_name;
    const char *volk_16i_32fc_dot_prod_32fc_impl_names[22];
    const int volk_16i_32fc_dot_prod_32fc_impl_deps[22];
    const bool volk_16i_32fc_dot_prod_32fc_impl_alignment[22];
    const p_16i_32fc_dot_prod_32fc volk_16i_32fc_dot_prod_32fc_impls[22];
    const size_t volk_16i_32fc_dot_prod_32fc_n_impls;
    const char *volk_8i_s32f_convert_32f_name;
    const char *volk_8i_s32f_convert_32f_impl_names[22];
    const int volk_8i_s32f_convert_32f_impl_deps[22];
    const bool volk_8i_s32f_convert_32f_impl_alignment[22];
    const p_8i_s32f_convert_32f volk_8i_s32f_convert_32f_impls[22];
    const size_t volk_8i_s32f_convert_32f_n_impls;
    const char *volk_16ic_magnitude_16i_name;
    const char *volk_16ic_magnitude_16i_impl_names[22];
    const int volk_16ic_magnitude_16i_impl_deps[22];
    const bool volk_16ic_magnitude_16i_impl_alignment[22];
    const p_16ic_magnitude_16i volk_16ic_magnitude_16i_impls[22];
    const size_t volk_16ic_magnitude_16i_n_impls;
    const char *volk_16u_byteswappuppet_16u_name;
    const char *volk_16u_byteswappuppet_16u_impl_names[22];
    const int volk_16u_byteswappuppet_16u_impl_deps[22];
    const bool volk_16u_byteswappuppet_16u_impl_alignment[22];
    const p_16u_byteswappuppet_16u volk_16u_byteswappuppet_16u_impls[22];
    const size_t volk_16u_byteswappuppet_16u_n_impls;
    const char *volk_32fc_x2_square_dist_32f_name;
    const char *volk_32fc_x2_square_dist_32f_impl_names[22];
    const int volk_32fc_x2_square_dist_32f_impl_deps[22];
    const bool volk_32fc_x2_square_dist_32f_impl_alignment[22];
    const p_32fc_x2_square_dist_32f volk_32fc_x2_square_dist_32f_impls[22];
    const size_t volk_32fc_x2_square_dist_32f_n_impls;
    const char *volk_32fc_deinterleave_32f_x2_name;
    const char *volk_32fc_deinterleave_32f_x2_impl_names[22];
    const int volk_32fc_deinterleave_32f_x2_impl_deps[22];
    const bool volk_32fc_deinterleave_32f_x2_impl_alignment[22];
    const p_32fc_deinterleave_32f_x2 volk_32fc_deinterleave_32f_x2_impls[22];
    const size_t volk_32fc_deinterleave_32f_x2_n_impls;
    const char *volk_64u_popcntpuppet_64u_name;
    const char *volk_64u_popcntpuppet_64u_impl_names[22];
    const int volk_64u_popcntpuppet_64u_impl_deps[22];
    const bool volk_64u_popcntpuppet_64u_impl_alignment[22];
    const p_64u_popcntpuppet_64u volk_64u_popcntpuppet_64u_impls[22];
    const size_t volk_64u_popcntpuppet_64u_n_impls;
    const char *volk_8u_conv_k7_r2puppet_8u_name;
    const char *volk_8u_conv_k7_r2puppet_8u_impl_names[22];
    const int volk_8u_conv_k7_r2puppet_8u_impl_deps[22];
    const bool volk_8u_conv_k7_r2puppet_8u_impl_alignment[22];
    const p_8u_conv_k7_r2puppet_8u volk_8u_conv_k7_r2puppet_8u_impls[22];
    const size_t volk_8u_conv_k7_r2puppet_8u_n_impls;
    const char *volk_16ic_x2_dot_prod_16ic_name;
    const char *volk_16ic_x2_dot_prod_16ic_impl_names[22];
    const int volk_16ic_x2_dot_prod_16ic_impl_deps[22];
    const bool volk_16ic_x2_dot_prod_16ic_impl_alignment[22];
    const p_16ic_x2_dot_prod_16ic volk_16ic_x2_dot_prod_16ic_impls[22];
    const size_t volk_16ic_x2_dot_prod_16ic_n_impls;
    const char *volk_32f_x2_subtract_32f_name;
    const char *volk_32f_x2_subtract_32f_impl_names[22];
    const int volk_32f_x2_subtract_32f_impl_deps[22];
    const bool volk_32f_x2_subtract_32f_impl_alignment[22];
    const p_32f_x2_subtract_32f volk_32f_x2_subtract_32f_impls[22];
    const size_t volk_32f_x2_subtract_32f_n_impls;
    const char *volk_32fc_s32f_power_spectrum_32f_name;
    const char *volk_32fc_s32f_power_spectrum_32f_impl_names[22];
    const int volk_32fc_s32f_power_spectrum_32f_impl_deps[22];
    const bool volk_32fc_s32f_power_spectrum_32f_impl_alignment[22];
    const p_32fc_s32f_power_spectrum_32f volk_32fc_s32f_power_spectrum_32f_impls[22];
    const size_t volk_32fc_s32f_power_spectrum_32f_n_impls;
    const char *volk_8ic_deinterleave_real_8i_name;
    const char *volk_8ic_deinterleave_real_8i_impl_names[22];
    const int volk_8ic_deinterleave_real_8i_impl_deps[22];
    const bool volk_8ic_deinterleave_real_8i_impl_alignment[22];
    const p_8ic_deinterleave_real_8i volk_8ic_deinterleave_real_8i_impls[22];
    const size_t volk_8ic_deinterleave_real_8i_n_impls;
    const char *volk_32f_x2_dot_prod_16i_name;
    const char *volk_32f_x2_dot_prod_16i_impl_names[22];
    const int volk_32f_x2_dot_prod_16i_impl_deps[22];
    const bool volk_32f_x2_dot_prod_16i_impl_alignment[22];
    const p_32f_x2_dot_prod_16i volk_32f_x2_dot_prod_16i_impls[22];
    const size_t volk_32f_x2_dot_prod_16i_n_impls;
    const char *volk_32f_binary_slicer_32i_name;
    const char *volk_32f_binary_slicer_32i_impl_names[22];
    const int volk_32f_binary_slicer_32i_impl_deps[22];
    const bool volk_32f_binary_slicer_32i_impl_alignment[22];
    const p_32f_binary_slicer_32i volk_32f_binary_slicer_32i_impls[22];
    const size_t volk_32f_binary_slicer_32i_n_impls;
    const char *volk_32f_x2_max_32f_name;
    const char *volk_32f_x2_max_32f_impl_names[22];
    const int volk_32f_x2_max_32f_impl_deps[22];
    const bool volk_32f_x2_max_32f_impl_alignment[22];
    const p_32f_x2_max_32f volk_32f_x2_max_32f_impls[22];
    const size_t volk_32f_x2_max_32f_n_impls;
    const char *volk_32fc_conjugate_32fc_name;
    const char *volk_32fc_conjugate_32fc_impl_names[22];
    const int volk_32fc_conjugate_32fc_impl_deps[22];
    const bool volk_32fc_conjugate_32fc_impl_alignment[22];
    const p_32fc_conjugate_32fc volk_32fc_conjugate_32fc_impls[22];
    const size_t volk_32fc_conjugate_32fc_n_impls;
    const char *volk_16ic_x2_multiply_16ic_name;
    const char *volk_16ic_x2_multiply_16ic_impl_names[22];
    const int volk_16ic_x2_multiply_16ic_impl_deps[22];
    const bool volk_16ic_x2_multiply_16ic_impl_alignment[22];
    const p_16ic_x2_multiply_16ic volk_16ic_x2_multiply_16ic_impls[22];
    const size_t volk_16ic_x2_multiply_16ic_n_impls;
    const char *volk_64f_x2_max_64f_name;
    const char *volk_64f_x2_max_64f_impl_names[22];
    const int volk_64f_x2_max_64f_impl_deps[22];
    const bool volk_64f_x2_max_64f_impl_alignment[22];
    const p_64f_x2_max_64f volk_64f_x2_max_64f_impls[22];
    const size_t volk_64f_x2_max_64f_n_impls;
    const char *volk_32fc_deinterleave_real_64f_name;
    const char *volk_32fc_deinterleave_real_64f_impl_names[22];
    const int volk_32fc_deinterleave_real_64f_impl_deps[22];
    const bool volk_32fc_deinterleave_real_64f_impl_alignment[22];
    const p_32fc_deinterleave_real_64f volk_32fc_deinterleave_real_64f_impls[22];
    const size_t volk_32fc_deinterleave_real_64f_n_impls;
    const char *volk_64u_byteswap_name;
    const char *volk_64u_byteswap_impl_names[22];
    const int volk_64u_byteswap_impl_deps[22];
    const bool volk_64u_byteswap_impl_alignment[22];
    const p_64u_byteswap volk_64u_byteswap_impls[22];
    const size_t volk_64u_byteswap_n_impls;
    const char *volk_32f_s32f_stddev_32f_name;
    const char *volk_32f_s32f_stddev_32f_impl_names[22];
    const int volk_32f_s32f_stddev_32f_impl_deps[22];
    const bool volk_32f_s32f_stddev_32f_impl_alignment[22];
    const p_32f_s32f_stddev_32f volk_32f_s32f_stddev_32f_impls[22];
    const size_t volk_32f_s32f_stddev_32f_n_impls;
    const char *volk_32f_tan_32f_name;
    const char *volk_32f_tan_32f_impl_names[22];
    const int volk_32f_tan_32f_impl_deps[22];
    const bool volk_32f_tan_32f_impl_alignment[22];
    const p_32f_tan_32f volk_32f_tan_32f_impls[22];
    const size_t volk_32f_tan_32f_n_impls;
    const char *volk_8ic_s32f_deinterleave_real_32f_name;
    const char *volk_8ic_s32f_deinterleave_real_32f_impl_names[22];
    const int volk_8ic_s32f_deinterleave_real_32f_impl_deps[22];
    const bool volk_8ic_s32f_deinterleave_real_32f_impl_alignment[22];
    const p_8ic_s32f_deinterleave_real_32f volk_8ic_s32f_deinterleave_real_32f_impls[22];
    const size_t volk_8ic_s32f_deinterleave_real_32f_n_impls;
    const char *volk_8ic_deinterleave_16i_x2_name;
    const char *volk_8ic_deinterleave_16i_x2_impl_names[22];
    const int volk_8ic_deinterleave_16i_x2_impl_deps[22];
    const bool volk_8ic_deinterleave_16i_x2_impl_alignment[22];
    const p_8ic_deinterleave_16i_x2 volk_8ic_deinterleave_16i_x2_impls[22];
    const size_t volk_8ic_deinterleave_16i_x2_n_impls;
    const char *volk_32fc_s32f_magnitude_16i_name;
    const char *volk_32fc_s32f_magnitude_16i_impl_names[22];
    const int volk_32fc_s32f_magnitude_16i_impl_deps[22];
    const bool volk_32fc_s32f_magnitude_16i_impl_alignment[22];
    const p_32fc_s32f_magnitude_16i volk_32fc_s32f_magnitude_16i_impls[22];
    const size_t volk_32fc_s32f_magnitude_16i_n_impls;
    const char *volk_16i_convert_8i_name;
    const char *volk_16i_convert_8i_impl_names[22];
    const int volk_16i_convert_8i_impl_deps[22];
    const bool volk_16i_convert_8i_impl_alignment[22];
    const p_16i_convert_8i volk_16i_convert_8i_impls[22];
    const size_t volk_16i_convert_8i_n_impls;
    const char *volk_32fc_index_max_32u_name;
    const char *volk_32fc_index_max_32u_impl_names[22];
    const int volk_32fc_index_max_32u_impl_deps[22];
    const bool volk_32fc_index_max_32u_impl_alignment[22];
    const p_32fc_index_max_32u volk_32fc_index_max_32u_impls[22];
    const size_t volk_32fc_index_max_32u_n_impls;
    const char *volk_32f_s32f_normalize_name;
    const char *volk_32f_s32f_normalize_impl_names[22];
    const int volk_32f_s32f_normalize_impl_deps[22];
    const bool volk_32f_s32f_normalize_impl_alignment[22];
    const p_32f_s32f_normalize volk_32f_s32f_normalize_impls[22];
    const size_t volk_32f_s32f_normalize_n_impls;
    const char *volk_16ic_deinterleave_real_16i_name;
    const char *volk_16ic_deinterleave_real_16i_impl_names[22];
    const int volk_16ic_deinterleave_real_16i_impl_deps[22];
    const bool volk_16ic_deinterleave_real_16i_impl_alignment[22];
    const p_16ic_deinterleave_real_16i volk_16ic_deinterleave_real_16i_impls[22];
    const size_t volk_16ic_deinterleave_real_16i_n_impls;
    const char *volk_32f_null_32f_name;
    const char *volk_32f_null_32f_impl_names[22];
    const int volk_32f_null_32f_impl_deps[22];
    const bool volk_32f_null_32f_impl_alignment[22];
    const p_32f_null_32f volk_32f_null_32f_impls[22];
    const size_t volk_32f_null_32f_n_impls;
    const char *volk_16i_branch_4_state_8_name;
    const char *volk_16i_branch_4_state_8_impl_names[22];
    const int volk_16i_branch_4_state_8_impl_deps[22];
    const bool volk_16i_branch_4_state_8_impl_alignment[22];
    const p_16i_branch_4_state_8 volk_16i_branch_4_state_8_impls[22];
    const size_t volk_16i_branch_4_state_8_n_impls;
    const char *volk_32fc_x2_multiply_conjugate_32fc_name;
    const char *volk_32fc_x2_multiply_conjugate_32fc_impl_names[22];
    const int volk_32fc_x2_multiply_conjugate_32fc_impl_deps[22];
    const bool volk_32fc_x2_multiply_conjugate_32fc_impl_alignment[22];
    const p_32fc_x2_multiply_conjugate_32fc volk_32fc_x2_multiply_conjugate_32fc_impls[22];
    const size_t volk_32fc_x2_multiply_conjugate_32fc_n_impls;
    const char *volk_32f_x2_add_32f_name;
    const char *volk_32f_x2_add_32f_impl_names[22];
    const int volk_32f_x2_add_32f_impl_deps[22];
    const bool volk_32f_x2_add_32f_impl_alignment[22];
    const p_32f_x2_add_32f volk_32f_x2_add_32f_impls[22];
    const size_t volk_32f_x2_add_32f_n_impls;
    const char *volk_32fc_index_max_16u_name;
    const char *volk_32fc_index_max_16u_impl_names[22];
    const int volk_32fc_index_max_16u_impl_deps[22];
    const bool volk_32fc_index_max_16u_impl_alignment[22];
    const p_32fc_index_max_16u volk_32fc_index_max_16u_impls[22];
    const size_t volk_32fc_index_max_16u_n_impls;
    const char *volk_32f_x2_fm_detectpuppet_32f_name;
    const char *volk_32f_x2_fm_detectpuppet_32f_impl_names[22];
    const int volk_32f_x2_fm_detectpuppet_32f_impl_deps[22];
    const bool volk_32f_x2_fm_detectpuppet_32f_impl_alignment[22];
    const p_32f_x2_fm_detectpuppet_32f volk_32f_x2_fm_detectpuppet_32f_impls[22];
    const size_t volk_32f_x2_fm_detectpuppet_32f_n_impls;
    const char *volk_8ic_x2_s32f_multiply_conjugate_32fc_name;
    const char *volk_8ic_x2_s32f_multiply_conjugate_32fc_impl_names[22];
    const int volk_8ic_x2_s32f_multiply_conjugate_32fc_impl_deps[22];
    const bool volk_8ic_x2_s32f_multiply_conjugate_32fc_impl_alignment[22];
    const p_8ic_x2_s32f_multiply_conjugate_32fc volk_8ic_x2_s32f_multiply_conjugate_32fc_impls[22];
    const size_t volk_8ic_x2_s32f_multiply_conjugate_32fc_n_impls;
    const char *volk_32fc_deinterleave_real_32f_name;
    const char *volk_32fc_deinterleave_real_32f_impl_names[22];
    const int volk_32fc_deinterleave_real_32f_impl_deps[22];
    const bool volk_32fc_deinterleave_real_32f_impl_alignment[22];
    const p_32fc_deinterleave_real_32f volk_32fc_deinterleave_real_32f_impls[22];
    const size_t volk_32fc_deinterleave_real_32f_n_impls;
    const char *volk_32f_x2_multiply_32f_name;
    const char *volk_32f_x2_multiply_32f_impl_names[22];
    const int volk_32f_x2_multiply_32f_impl_deps[22];
    const bool volk_32f_x2_multiply_32f_impl_alignment[22];
    const p_32f_x2_multiply_32f volk_32f_x2_multiply_32f_impls[22];
    const size_t volk_32f_x2_multiply_32f_n_impls;
    const char *volk_32fc_s32fc_multiply_32fc_name;
    const char *volk_32fc_s32fc_multiply_32fc_impl_names[22];
    const int volk_32fc_s32fc_multiply_32fc_impl_deps[22];
    const bool volk_32fc_s32fc_multiply_32fc_impl_alignment[22];
    const p_32fc_s32fc_multiply_32fc volk_32fc_s32fc_multiply_32fc_impls[22];
    const size_t volk_32fc_s32fc_multiply_32fc_n_impls;
    const char *volk_16i_x5_add_quad_16i_x4_name;
    const char *volk_16i_x5_add_quad_16i_x4_impl_names[22];
    const int volk_16i_x5_add_quad_16i_x4_impl_deps[22];
    const bool volk_16i_x5_add_quad_16i_x4_impl_alignment[22];
    const p_16i_x5_add_quad_16i_x4 volk_16i_x5_add_quad_16i_x4_impls[22];
    const size_t volk_16i_x5_add_quad_16i_x4_n_impls;
    const char *volk_32f_tanh_32f_name;
    const char *volk_32f_tanh_32f_impl_names[22];
    const int volk_32f_tanh_32f_impl_deps[22];
    const bool volk_32f_tanh_32f_impl_alignment[22];
    const p_32f_tanh_32f volk_32f_tanh_32f_impls[22];
    const size_t volk_32f_tanh_32f_n_impls;
    const char *volk_16ic_s32f_magnitude_32f_name;
    const char *volk_16ic_s32f_magnitude_32f_impl_names[22];
    const int volk_16ic_s32f_magnitude_32f_impl_deps[22];
    const bool volk_16ic_s32f_magnitude_32f_impl_alignment[22];
    const p_16ic_s32f_magnitude_32f volk_16ic_s32f_magnitude_32f_impls[22];
    const size_t volk_16ic_s32f_magnitude_32f_n_impls;
    const char *volk_32fc_magnitude_squared_32f_name;
    const char *volk_32fc_magnitude_squared_32f_impl_names[22];
    const int volk_32fc_magnitude_squared_32f_impl_deps[22];
    const bool volk_32fc_magnitude_squared_32f_impl_alignment[22];
    const p_32fc_magnitude_squared_32f volk_32fc_magnitude_squared_32f_impls[22];
    const size_t volk_32fc_magnitude_squared_32f_n_impls;
    const char *volk_8i_convert_16i_name;
    const char *volk_8i_convert_16i_impl_names[22];
    const int volk_8i_convert_16i_impl_deps[22];
    const bool volk_8i_convert_16i_impl_alignment[22];
    const p_8i_convert_16i volk_8i_convert_16i_impls[22];
    const size_t volk_8i_convert_16i_n_impls;
    const char *volk_64f_x2_min_64f_name;
    const char *volk_64f_x2_min_64f_impl_names[22];
    const int volk_64f_x2_min_64f_impl_deps[22];
    const bool volk_64f_x2_min_64f_impl_alignment[22];
    const p_64f_x2_min_64f volk_64f_x2_min_64f_impls[22];
    const size_t volk_64f_x2_min_64f_n_impls;
    const char *volk_32f_expfast_32f_name;
    const char *volk_32f_expfast_32f_impl_names[22];
    const int volk_32f_expfast_32f_impl_deps[22];
    const bool volk_32f_expfast_32f_impl_alignment[22];
    const p_32f_expfast_32f volk_32f_expfast_32f_impls[22];
    const size_t volk_32f_expfast_32f_n_impls;
    const char *volk_32f_log2_32f_name;
    const char *volk_32f_log2_32f_impl_names[22];
    const int volk_32f_log2_32f_impl_deps[22];
    const bool volk_32f_log2_32f_impl_alignment[22];
    const p_32f_log2_32f volk_32f_log2_32f_impls[22];
    const size_t volk_32f_log2_32f_n_impls;
    const char *volk_8ic_s32f_deinterleave_32f_x2_name;
    const char *volk_8ic_s32f_deinterleave_32f_x2_impl_names[22];
    const int volk_8ic_s32f_deinterleave_32f_x2_impl_deps[22];
    const bool volk_8ic_s32f_deinterleave_32f_x2_impl_alignment[22];
    const p_8ic_s32f_deinterleave_32f_x2 volk_8ic_s32f_deinterleave_32f_x2_impls[22];
    const size_t volk_8ic_s32f_deinterleave_32f_x2_n_impls;
    const char *volk_32f_atan_32f_name;
    const char *volk_32f_atan_32f_impl_names[22];
    const int volk_32f_atan_32f_impl_deps[22];
    const bool volk_32f_atan_32f_impl_alignment[22];
    const p_32f_atan_32f volk_32f_atan_32f_impls[22];
    const size_t volk_32f_atan_32f_n_impls;
    const char *volk_32f_asin_32f_name;
    const char *volk_32f_asin_32f_impl_names[22];
    const int volk_32f_asin_32f_impl_deps[22];
    const bool volk_32f_asin_32f_impl_alignment[22];
    const p_32f_asin_32f volk_32f_asin_32f_impls[22];
    const size_t volk_32f_asin_32f_n_impls;
    const char *volk_32fc_32f_dot_prod_32fc_name;
    const char *volk_32fc_32f_dot_prod_32fc_impl_names[22];
    const int volk_32fc_32f_dot_prod_32fc_impl_deps[22];
    const bool volk_32fc_32f_dot_prod_32fc_impl_alignment[22];
    const p_32fc_32f_dot_prod_32fc volk_32fc_32f_dot_prod_32fc_impls[22];
    const size_t volk_32fc_32f_dot_prod_32fc_n_impls;
    const char *volk_32fc_s32f_x2_power_spectral_density_32f_name;
    const char *volk_32fc_s32f_x2_power_spectral_density_32f_impl_names[22];
    const int volk_32fc_s32f_x2_power_spectral_density_32f_impl_deps[22];
    const bool volk_32fc_s32f_x2_power_spectral_density_32f_impl_alignment[22];
    const p_32fc_s32f_x2_power_spectral_density_32f volk_32fc_s32f_x2_power_spectral_density_32f_impls[22];
    const size_t volk_32fc_s32f_x2_power_spectral_density_32f_n_impls;
    const char *volk_32f_convert_64f_name;
    const char *volk_32f_convert_64f_impl_names[22];
    const int volk_32f_convert_64f_impl_deps[22];
    const bool volk_32f_convert_64f_impl_alignment[22];
    const p_32f_convert_64f volk_32f_convert_64f_impls[22];
    const size_t volk_32f_convert_64f_n_impls;
    const char *volk_32f_accumulator_s32f_name;
    const char *volk_32f_accumulator_s32f_impl_names[22];
    const int volk_32f_accumulator_s32f_impl_deps[22];
    const bool volk_32f_accumulator_s32f_impl_alignment[22];
    const p_32f_accumulator_s32f volk_32f_accumulator_s32f_impls[22];
    const size_t volk_32f_accumulator_s32f_n_impls;
    const char *volk_32fc_s32fc_x2_rotator_32fc_name;
    const char *volk_32fc_s32fc_x2_rotator_32fc_impl_names[22];
    const int volk_32fc_s32fc_x2_rotator_32fc_impl_deps[22];
    const bool volk_32fc_s32fc_x2_rotator_32fc_impl_alignment[22];
    const p_32fc_s32fc_x2_rotator_32fc volk_32fc_s32fc_x2_rotator_32fc_impls[22];
    const size_t volk_32fc_s32fc_x2_rotator_32fc_n_impls;
    const char *volk_32u_byteswappuppet_32u_name;
    const char *volk_32u_byteswappuppet_32u_impl_names[22];
    const int volk_32u_byteswappuppet_32u_impl_deps[22];
    const bool volk_32u_byteswappuppet_32u_impl_alignment[22];
    const p_32u_byteswappuppet_32u volk_32u_byteswappuppet_32u_impls[22];
    const size_t volk_32u_byteswappuppet_32u_n_impls;
    const char *volk_16i_s32f_convert_32f_name;
    const char *volk_16i_s32f_convert_32f_impl_names[22];
    const int volk_16i_s32f_convert_32f_impl_deps[22];
    const bool volk_16i_s32f_convert_32f_impl_alignment[22];
    const p_16i_s32f_convert_32f volk_16i_s32f_convert_32f_impls[22];
    const size_t volk_16i_s32f_convert_32f_n_impls;
    const char *volk_16i_max_star_horizontal_16i_name;
    const char *volk_16i_max_star_horizontal_16i_impl_names[22];
    const int volk_16i_max_star_horizontal_16i_impl_deps[22];
    const bool volk_16i_max_star_horizontal_16i_impl_alignment[22];
    const p_16i_max_star_horizontal_16i volk_16i_max_star_horizontal_16i_impls[22];
    const size_t volk_16i_max_star_horizontal_16i_n_impls;
    const char *volk_8ic_deinterleave_real_16i_name;
    const char *volk_8ic_deinterleave_real_16i_impl_names[22];
    const int volk_8ic_deinterleave_real_16i_impl_deps[22];
    const bool volk_8ic_deinterleave_real_16i_impl_alignment[22];
    const p_8ic_deinterleave_real_16i volk_8ic_deinterleave_real_16i_impls[22];
    const size_t volk_8ic_deinterleave_real_16i_n_impls;
    const char *volk_32fc_x2_dot_prod_32fc_name;
    const char *volk_32fc_x2_dot_prod_32fc_impl_names[22];
    const int volk_32fc_x2_dot_prod_32fc_impl_deps[22];
    const bool volk_32fc_x2_dot_prod_32fc_impl_alignment[22];
    const p_32fc_x2_dot_prod_32fc volk_32fc_x2_dot_prod_32fc_impls[22];
    const size_t volk_32fc_x2_dot_prod_32fc_n_impls;
    const char *volk_32f_s32f_calc_spectral_noise_floor_32f_name;
    const char *volk_32f_s32f_calc_spectral_noise_floor_32f_impl_names[22];
    const int volk_32f_s32f_calc_spectral_noise_floor_32f_impl_deps[22];
    const bool volk_32f_s32f_calc_spectral_noise_floor_32f_impl_alignment[22];
    const p_32f_s32f_calc_spectral_noise_floor_32f volk_32f_s32f_calc_spectral_noise_floor_32f_impls[22];
    const size_t volk_32f_s32f_calc_spectral_noise_floor_32f_n_impls;
    const char *volk_16ic_convert_32fc_name;
    const char *volk_16ic_convert_32fc_impl_names[22];
    const int volk_16ic_convert_32fc_impl_deps[22];
    const bool volk_16ic_convert_32fc_impl_alignment[22];
    const p_16ic_convert_32fc volk_16ic_convert_32fc_impls[22];
    const size_t volk_16ic_convert_32fc_n_impls;
    const char *volk_32fc_magnitude_32f_name;
    const char *volk_32fc_magnitude_32f_impl_names[22];
    const int volk_32fc_magnitude_32f_impl_deps[22];
    const bool volk_32fc_magnitude_32f_impl_alignment[22];
    const p_32fc_magnitude_32f volk_32fc_magnitude_32f_impls[22];
    const size_t volk_32fc_magnitude_32f_n_impls;
    const char *volk_64f_convert_32f_name;
    const char *volk_64f_convert_32f_impl_names[22];
    const int volk_64f_convert_32f_impl_deps[22];
    const bool volk_64f_convert_32f_impl_alignment[22];
    const p_64f_convert_32f volk_64f_convert_32f_impls[22];
    const size_t volk_64f_convert_32f_n_impls;
    const char *volk_32fc_x2_conjugate_dot_prod_32fc_name;
    const char *volk_32fc_x2_conjugate_dot_prod_32fc_impl_names[22];
    const int volk_32fc_x2_conjugate_dot_prod_32fc_impl_deps[22];
    const bool volk_32fc_x2_conjugate_dot_prod_32fc_impl_alignment[22];
    const p_32fc_x2_conjugate_dot_prod_32fc volk_32fc_x2_conjugate_dot_prod_32fc_impls[22];
    const size_t volk_32fc_x2_conjugate_dot_prod_32fc_n_impls;
    const char *volk_32f_binary_slicer_8i_name;
    const char *volk_32f_binary_slicer_8i_impl_names[22];
    const int volk_32f_binary_slicer_8i_impl_deps[22];
    const bool volk_32f_binary_slicer_8i_impl_alignment[22];
    const p_32f_binary_slicer_8i volk_32f_binary_slicer_8i_impls[22];
    const size_t volk_32f_binary_slicer_8i_n_impls;
    const char *volk_32f_x3_sum_of_poly_32f_name;
    const char *volk_32f_x3_sum_of_poly_32f_impl_names[22];
    const int volk_32f_x3_sum_of_poly_32f_impl_deps[22];
    const bool volk_32f_x3_sum_of_poly_32f_impl_alignment[22];
    const p_32f_x3_sum_of_poly_32f volk_32f_x3_sum_of_poly_32f_impls[22];
    const size_t volk_32f_x3_sum_of_poly_32f_n_impls;
    const char *volk_32f_x2_interleave_32fc_name;
    const char *volk_32f_x2_interleave_32fc_impl_names[22];
    const int volk_32f_x2_interleave_32fc_impl_deps[22];
    const bool volk_32f_x2_interleave_32fc_impl_alignment[22];
    const p_32f_x2_interleave_32fc volk_32f_x2_interleave_32fc_impls[22];
    const size_t volk_32f_x2_interleave_32fc_n_impls;
    const char *volk_32fc_convert_16ic_name;
    const char *volk_32fc_convert_16ic_impl_names[22];
    const int volk_32fc_convert_16ic_impl_deps[22];
    const bool volk_32fc_convert_16ic_impl_alignment[22];
    const p_32fc_convert_16ic volk_32fc_convert_16ic_impls[22];
    const size_t volk_32fc_convert_16ic_n_impls;
    const char *volk_8u_x2_encodeframepolar_8u_name;
    const char *volk_8u_x2_encodeframepolar_8u_impl_names[22];
    const int volk_8u_x2_encodeframepolar_8u_impl_deps[22];
    const bool volk_8u_x2_encodeframepolar_8u_impl_alignment[22];
    const p_8u_x2_encodeframepolar_8u volk_8u_x2_encodeframepolar_8u_impls[22];
    const size_t volk_8u_x2_encodeframepolar_8u_n_impls;
    const char *volk_32f_invsqrt_32f_name;
    const char *volk_32f_invsqrt_32f_impl_names[22];
    const int volk_32f_invsqrt_32f_impl_deps[22];
    const bool volk_32f_invsqrt_32f_impl_alignment[22];
    const p_32f_invsqrt_32f volk_32f_invsqrt_32f_impls[22];
    const size_t volk_32f_invsqrt_32f_n_impls;
};

#ifdef LV_MACHINE_GENERIC_ORC
extern struct volk_machine volk_machine_generic_orc;
#endif
#ifdef LV_MACHINE_GENERIC
extern struct volk_machine volk_machine_generic;
#endif
#ifdef LV_MACHINE_NEON_SOFTFP_ORC
extern struct volk_machine volk_machine_neon_softfp_orc;
#endif
#ifdef LV_MACHINE_NEON_SOFTFP
extern struct volk_machine volk_machine_neon_softfp;
#endif
#ifdef LV_MACHINE_NEON_HARDFP_ORC
extern struct volk_machine volk_machine_neon_hardfp_orc;
#endif
#ifdef LV_MACHINE_NEON_HARDFP
extern struct volk_machine volk_machine_neon_hardfp;
#endif
#ifdef LV_MACHINE_SSE2_32_MMX_ORC
extern struct volk_machine volk_machine_sse2_32_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE2_32_MMX
extern struct volk_machine volk_machine_sse2_32_mmx;
#endif
#ifdef LV_MACHINE_SSE2_32_ORC
extern struct volk_machine volk_machine_sse2_32_orc;
#endif
#ifdef LV_MACHINE_SSE2_32
extern struct volk_machine volk_machine_sse2_32;
#endif
#ifdef LV_MACHINE_SSE2_64_MMX_ORC
extern struct volk_machine volk_machine_sse2_64_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE2_64_MMX
extern struct volk_machine volk_machine_sse2_64_mmx;
#endif
#ifdef LV_MACHINE_SSE2_64_ORC
extern struct volk_machine volk_machine_sse2_64_orc;
#endif
#ifdef LV_MACHINE_SSE2_64
extern struct volk_machine volk_machine_sse2_64;
#endif
#ifdef LV_MACHINE_SSE2_MMX_ORC
extern struct volk_machine volk_machine_sse2_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE2_MMX
extern struct volk_machine volk_machine_sse2_mmx;
#endif
#ifdef LV_MACHINE_SSE2_ORC
extern struct volk_machine volk_machine_sse2_orc;
#endif
#ifdef LV_MACHINE_SSE2
extern struct volk_machine volk_machine_sse2;
#endif
#ifdef LV_MACHINE_SSE3_32_MMX_ORC
extern struct volk_machine volk_machine_sse3_32_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE3_32_MMX
extern struct volk_machine volk_machine_sse3_32_mmx;
#endif
#ifdef LV_MACHINE_SSE3_32_ORC
extern struct volk_machine volk_machine_sse3_32_orc;
#endif
#ifdef LV_MACHINE_SSE3_32
extern struct volk_machine volk_machine_sse3_32;
#endif
#ifdef LV_MACHINE_SSE3_64_MMX_ORC
extern struct volk_machine volk_machine_sse3_64_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE3_64_MMX
extern struct volk_machine volk_machine_sse3_64_mmx;
#endif
#ifdef LV_MACHINE_SSE3_64_ORC
extern struct volk_machine volk_machine_sse3_64_orc;
#endif
#ifdef LV_MACHINE_SSE3_64
extern struct volk_machine volk_machine_sse3_64;
#endif
#ifdef LV_MACHINE_SSE3_MMX_ORC
extern struct volk_machine volk_machine_sse3_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE3_MMX
extern struct volk_machine volk_machine_sse3_mmx;
#endif
#ifdef LV_MACHINE_SSE3_ORC
extern struct volk_machine volk_machine_sse3_orc;
#endif
#ifdef LV_MACHINE_SSE3
extern struct volk_machine volk_machine_sse3;
#endif
#ifdef LV_MACHINE_SSSE3_32_MMX_ORC
extern struct volk_machine volk_machine_ssse3_32_mmx_orc;
#endif
#ifdef LV_MACHINE_SSSE3_32_MMX
extern struct volk_machine volk_machine_ssse3_32_mmx;
#endif
#ifdef LV_MACHINE_SSSE3_32_ORC
extern struct volk_machine volk_machine_ssse3_32_orc;
#endif
#ifdef LV_MACHINE_SSSE3_32
extern struct volk_machine volk_machine_ssse3_32;
#endif
#ifdef LV_MACHINE_SSSE3_64_MMX_ORC
extern struct volk_machine volk_machine_ssse3_64_mmx_orc;
#endif
#ifdef LV_MACHINE_SSSE3_64_MMX
extern struct volk_machine volk_machine_ssse3_64_mmx;
#endif
#ifdef LV_MACHINE_SSSE3_64_ORC
extern struct volk_machine volk_machine_ssse3_64_orc;
#endif
#ifdef LV_MACHINE_SSSE3_64
extern struct volk_machine volk_machine_ssse3_64;
#endif
#ifdef LV_MACHINE_SSSE3_MMX_ORC
extern struct volk_machine volk_machine_ssse3_mmx_orc;
#endif
#ifdef LV_MACHINE_SSSE3_MMX
extern struct volk_machine volk_machine_ssse3_mmx;
#endif
#ifdef LV_MACHINE_SSSE3_ORC
extern struct volk_machine volk_machine_ssse3_orc;
#endif
#ifdef LV_MACHINE_SSSE3
extern struct volk_machine volk_machine_ssse3;
#endif
#ifdef LV_MACHINE_SSE4_A_32_MMX_ORC
extern struct volk_machine volk_machine_sse4_a_32_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_A_32_MMX
extern struct volk_machine volk_machine_sse4_a_32_mmx;
#endif
#ifdef LV_MACHINE_SSE4_A_32_ORC
extern struct volk_machine volk_machine_sse4_a_32_orc;
#endif
#ifdef LV_MACHINE_SSE4_A_32
extern struct volk_machine volk_machine_sse4_a_32;
#endif
#ifdef LV_MACHINE_SSE4_A_64_MMX_ORC
extern struct volk_machine volk_machine_sse4_a_64_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_A_64_MMX
extern struct volk_machine volk_machine_sse4_a_64_mmx;
#endif
#ifdef LV_MACHINE_SSE4_A_64_ORC
extern struct volk_machine volk_machine_sse4_a_64_orc;
#endif
#ifdef LV_MACHINE_SSE4_A_64
extern struct volk_machine volk_machine_sse4_a_64;
#endif
#ifdef LV_MACHINE_SSE4_A_MMX_ORC
extern struct volk_machine volk_machine_sse4_a_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_A_MMX
extern struct volk_machine volk_machine_sse4_a_mmx;
#endif
#ifdef LV_MACHINE_SSE4_A_ORC
extern struct volk_machine volk_machine_sse4_a_orc;
#endif
#ifdef LV_MACHINE_SSE4_A
extern struct volk_machine volk_machine_sse4_a;
#endif
#ifdef LV_MACHINE_SSE4_1_32_MMX_ORC
extern struct volk_machine volk_machine_sse4_1_32_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_1_32_MMX
extern struct volk_machine volk_machine_sse4_1_32_mmx;
#endif
#ifdef LV_MACHINE_SSE4_1_32_ORC
extern struct volk_machine volk_machine_sse4_1_32_orc;
#endif
#ifdef LV_MACHINE_SSE4_1_32
extern struct volk_machine volk_machine_sse4_1_32;
#endif
#ifdef LV_MACHINE_SSE4_1_64_MMX_ORC
extern struct volk_machine volk_machine_sse4_1_64_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_1_64_MMX
extern struct volk_machine volk_machine_sse4_1_64_mmx;
#endif
#ifdef LV_MACHINE_SSE4_1_64_ORC
extern struct volk_machine volk_machine_sse4_1_64_orc;
#endif
#ifdef LV_MACHINE_SSE4_1_64
extern struct volk_machine volk_machine_sse4_1_64;
#endif
#ifdef LV_MACHINE_SSE4_1_MMX_ORC
extern struct volk_machine volk_machine_sse4_1_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_1_MMX
extern struct volk_machine volk_machine_sse4_1_mmx;
#endif
#ifdef LV_MACHINE_SSE4_1_ORC
extern struct volk_machine volk_machine_sse4_1_orc;
#endif
#ifdef LV_MACHINE_SSE4_1
extern struct volk_machine volk_machine_sse4_1;
#endif
#ifdef LV_MACHINE_SSE4_2_32_MMX_ORC
extern struct volk_machine volk_machine_sse4_2_32_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_2_32_MMX
extern struct volk_machine volk_machine_sse4_2_32_mmx;
#endif
#ifdef LV_MACHINE_SSE4_2_32_ORC
extern struct volk_machine volk_machine_sse4_2_32_orc;
#endif
#ifdef LV_MACHINE_SSE4_2_32
extern struct volk_machine volk_machine_sse4_2_32;
#endif
#ifdef LV_MACHINE_SSE4_2_64_MMX_ORC
extern struct volk_machine volk_machine_sse4_2_64_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_2_64_MMX
extern struct volk_machine volk_machine_sse4_2_64_mmx;
#endif
#ifdef LV_MACHINE_SSE4_2_64_ORC
extern struct volk_machine volk_machine_sse4_2_64_orc;
#endif
#ifdef LV_MACHINE_SSE4_2_64
extern struct volk_machine volk_machine_sse4_2_64;
#endif
#ifdef LV_MACHINE_SSE4_2_MMX_ORC
extern struct volk_machine volk_machine_sse4_2_mmx_orc;
#endif
#ifdef LV_MACHINE_SSE4_2_MMX
extern struct volk_machine volk_machine_sse4_2_mmx;
#endif
#ifdef LV_MACHINE_SSE4_2_ORC
extern struct volk_machine volk_machine_sse4_2_orc;
#endif
#ifdef LV_MACHINE_SSE4_2
extern struct volk_machine volk_machine_sse4_2;
#endif
#ifdef LV_MACHINE_AVX_32_MMX_ORC
extern struct volk_machine volk_machine_avx_32_mmx_orc;
#endif
#ifdef LV_MACHINE_AVX_32_MMX
extern struct volk_machine volk_machine_avx_32_mmx;
#endif
#ifdef LV_MACHINE_AVX_32_ORC
extern struct volk_machine volk_machine_avx_32_orc;
#endif
#ifdef LV_MACHINE_AVX_32
extern struct volk_machine volk_machine_avx_32;
#endif
#ifdef LV_MACHINE_AVX_64_MMX_ORC
extern struct volk_machine volk_machine_avx_64_mmx_orc;
#endif
#ifdef LV_MACHINE_AVX_64_MMX
extern struct volk_machine volk_machine_avx_64_mmx;
#endif
#ifdef LV_MACHINE_AVX_64_ORC
extern struct volk_machine volk_machine_avx_64_orc;
#endif
#ifdef LV_MACHINE_AVX_64
extern struct volk_machine volk_machine_avx_64;
#endif
#ifdef LV_MACHINE_AVX_MMX_ORC
extern struct volk_machine volk_machine_avx_mmx_orc;
#endif
#ifdef LV_MACHINE_AVX_MMX
extern struct volk_machine volk_machine_avx_mmx;
#endif
#ifdef LV_MACHINE_AVX_ORC
extern struct volk_machine volk_machine_avx_orc;
#endif
#ifdef LV_MACHINE_AVX
extern struct volk_machine volk_machine_avx;
#endif
#ifdef LV_MACHINE_AVX2_32_MMX_ORC
extern struct volk_machine volk_machine_avx2_32_mmx_orc;
#endif
#ifdef LV_MACHINE_AVX2_32_MMX
extern struct volk_machine volk_machine_avx2_32_mmx;
#endif
#ifdef LV_MACHINE_AVX2_32_ORC
extern struct volk_machine volk_machine_avx2_32_orc;
#endif
#ifdef LV_MACHINE_AVX2_32
extern struct volk_machine volk_machine_avx2_32;
#endif
#ifdef LV_MACHINE_AVX2_64_MMX_ORC
extern struct volk_machine volk_machine_avx2_64_mmx_orc;
#endif
#ifdef LV_MACHINE_AVX2_64_MMX
extern struct volk_machine volk_machine_avx2_64_mmx;
#endif
#ifdef LV_MACHINE_AVX2_64_ORC
extern struct volk_machine volk_machine_avx2_64_orc;
#endif
#ifdef LV_MACHINE_AVX2_64
extern struct volk_machine volk_machine_avx2_64;
#endif
#ifdef LV_MACHINE_AVX2_MMX_ORC
extern struct volk_machine volk_machine_avx2_mmx_orc;
#endif
#ifdef LV_MACHINE_AVX2_MMX
extern struct volk_machine volk_machine_avx2_mmx;
#endif
#ifdef LV_MACHINE_AVX2_ORC
extern struct volk_machine volk_machine_avx2_orc;
#endif
#ifdef LV_MACHINE_AVX2
extern struct volk_machine volk_machine_avx2;
#endif

__VOLK_DECL_END

#endif //INCLUDED_LIBVOLK_MACHINES_H