#
# Copyright 2014 Ettus Research LLC
#

##################################################
# RFNoC Sources
##################################################
RFNOC_OOT_SRCS = \
$(addprefix /home/switchlanez/rfnoc/src/rfnoc-atsc_rx/rfnoc/fpga-src/, \
noc_block_fltpll.v \
noc_block_depad.v \
noc_block_dcragc.v \
noc_block_viterbi.v \
noc_block_deint.v \
noc_block_rsdec.v \
) \

